ddc_classification = {
  "metadata": {
    "title": "Dewey Decimal Classification (DDC) - OCLC Summaries",
    "description": "Complete DDC classification system with IDs and text descriptions",
    "source": "OCLC DDC 22 Summaries",
    "copyright": "© 2003 OCLC Online Computer Library Center, Inc.",
    "note": "Consult schedules for complete and exact headings",
    "levels": {
      "main_classes": "10 main classes (000-900)",
      "divisions": "100 divisions (010, 020, etc.)",
      "sections": "1000 sections (001, 002, etc.)"
    }
  },
  "main_classes": {
    "000": "Computer science, information & general works",
    "100": "Philosophy & psychology",
    "200": "Religion",
    "300": "Social sciences",
    "400": "Language",
    "500": "Science",
    "600": "Technology",
    "700": "Arts & recreation",
    "800": "Literature",
    "900": "History & geography"
  },
  "divisions": {
    "000": "Computer science, knowledge & systems",
    "010": "Bibliographies",
    "020": "Library & information sciences",
    "030": "Encyclopedias & books of facts",
    "040": "[Unassigned]",
    "050": "Magazines, journals & serials",
    "060": "Associations, organizations & museums",
    "070": "News media, journalism & publishing",
    "080": "Quotations",
    "090": "Manuscripts & rare books",
    "100": "Philosophy",
    "110": "Metaphysics",
    "120": "Epistemology",
    "130": "Parapsychology & occultism",
    "140": "Philosophical schools of thought",
    "150": "Psychology",
    "160": "Logic",
    "170": "Ethics",
    "180": "Ancient, medieval & eastern philosophy",
    "190": "Modern western philosophy",
    "200": "Religion",
    "210": "Philosophy & theory of religion",
    "220": "The Bible",
    "230": "Christianity & Christian theology",
    "240": "Christian practice & observance",
    "250": "Christian pastoral practice & religious orders",
    "260": "Christian organization, social work & worship",
    "270": "History of Christianity",
    "280": "Christian denominations",
    "290": "Other religions",
    "300": "Social sciences, sociology & anthropology",
    "310": "Statistics",
    "320": "Political science",
    "330": "Economics",
    "340": "Law",
    "350": "Public administration & military science",
    "360": "Social problems & social services",
    "370": "Education",
    "380": "Commerce, communications & transportation",
    "390": "Customs, etiquette & folklore",
    "400": "Language",
    "410": "Linguistics",
    "420": "English & Old English languages",
    "430": "German & related languages",
    "440": "French & related languages",
    "450": "Italian, Romanian & related languages",
    "460": "Spanish & Portuguese languages",
    "470": "Latin & Italic languages",
    "480": "Classical & modern Greek languages",
    "490": "Other languages",
    "500": "Science",
    "510": "Mathematics",
    "520": "Astronomy",
    "530": "Physics",
    "540": "Chemistry",
    "550": "Earth sciences & geology",
    "560": "Fossils & prehistoric life",
    "570": "Life sciences; biology",
    "580": "Plants (Botany)",
    "590": "Animals (Zoology)",
    "600": "Technology",
    "610": "Medicine & health",
    "620": "Engineering",
    "630": "Agriculture",
    "640": "Home & family management",
    "650": "Management & public relations",
    "660": "Chemical engineering",
    "670": "Manufacturing",
    "680": "Manufacture for specific uses",
    "690": "Building & construction",
    "700": "Arts",
    "710": "Landscaping & area planning",
    "720": "Architecture",
    "730": "Sculpture, ceramics & metalwork",
    "740": "Drawing & decorative arts",
    "750": "Painting",
    "760": "Graphic arts",
    "770": "Photography & computer art",
    "780": "Music",
    "790": "Sports, games & entertainment",
    "800": "Literature, rhetoric & criticism",
    "810": "American literature in English",
    "820": "English & Old English literatures",
    "830": "German & related literatures",
    "840": "French & related literatures",
    "850": "Italian, Romanian & related literatures",
    "860": "Spanish & Portuguese literatures",
    "870": "Latin & Italic literatures",
    "880": "Classical & modern Greek literatures",
    "890": "Other literatures",
    "900": "History",
    "910": "Geography & travel",
    "920": "Biography & genealogy",
    "930": "History of ancient world (to ca. 499)",
    "940": "History of Europe",
    "950": "History of Asia",
    "960": "History of Africa",
    "970": "History of North America",
    "980": "History of South America",
    "990": "History of other areas"
  },
  "sections": {
    "001": "Knowledge",
    "002": "The book",
    "003": "Systems",
    "004": "Data processing & computer science",
    "005": "Computer programming, programs & data",
    "006": "Special computer methods",
    "011": "Bibliographies",
    "012": "Bibliographies of individuals",
    "014": "Of anonymous & pseudonymous works",
    "015": "Bibliographies of works from specific places",
    "016": "Bibliographies of works on specific subjects",
    "017": "General subject catalogs",
    "018": "Catalogs arranged by author, date, etc.",
    "019": "Dictionary catalogs",
    "021": "Library relationships",
    "022": "Administration of physical plant",
    "023": "Personnel management",
    "025": "Library operations",
    "026": "Libraries for specific subjects",
    "027": "General libraries",
    "028": "Reading & use of other information media",
    "031": "Encyclopedias in American English",
    "032": "Encyclopedias in English",
    "033": "In other Germanic languages",
    "034": "Encyclopedias in French, Occitan & Catalan",
    "035": "In Italian, Romanian & related languages",
    "036": "Encyclopedias in Spanish & Portuguese",
    "037": "Encyclopedias in Slavic languages",
    "038": "Encyclopedias in Scandinavian languages",
    "039": "Encyclopedias in other languages",
    "051": "Serials in American English",
    "052": "Serials in English",
    "053": "Serials in other Germanic languages",
    "054": "Serials in French, Occitan & Catalan",
    "055": "In Italian, Romanian & related languages",
    "056": "Serials in Spanish & Portuguese",
    "057": "Serials in Slavic languages",
    "058": "Serials in Scandinavian languages",
    "059": "Serials in other languages",
    "061": "Organizations in North America",
    "062": "Organizations in British Isles; in England",
    "063": "Organizations in central Europe; in Germany",
    "064": "Organizations in France & Monaco",
    "065": "Organizations in Italy & adjacent islands",
    "066": "In Iberian Peninsula & adjacent islands",
    "067": "Organizations in eastern Europe; in Russia",
    "068": "Organizations in other geographic areas",
    "069": "Museum science",
    "071": "Newspapers in North America",
    "072": "Newspapers in British Isles; in England",
    "073": "Newspapers in central Europe; in Germany",
    "074": "Newspapers in France & Monaco",
    "075": "Newspapers in Italy & adjacent islands",
    "076": "In Iberian Peninsula & adjacent islands",
    "077": "Newspapers in eastern Europe; in Russia",
    "078": "Newspapers in Scandinavia",
    "079": "Newspapers in other geographic areas",
    "081": "Collections in American English",
    "082": "Collections in English",
    "083": "Collections in other Germanic languages",
    "084": "Collections in French, Occitan & Catalan",
    "085": "In Italian, Romanian & related languages",
    "086": "Collections in Spanish & Portuguese",
    "087": "Collections in Slavic languages",
    "088": "Collections in Scandinavian languages",
    "089": "Collections in other languages",
    "091": "Manuscripts",
    "092": "Block books",
    "093": "Incunabula",
    "094": "Printed books",
    "095": "Books notable for bindings",
    "096": "Books notable for illustrations",
    "097": "Books notable for ownership or origin",
    "098": "Prohibited works, forgeries & hoaxes",
    "099": "Books notable for format",
    "101": "Theory of philosophy",
    "102": "Miscellany",
    "103": "Dictionaries & encyclopedias",
    "105": "Serial publications",
    "106": "Organizations & management",
    "107": "Education, research & related topics",
    "108": "Kinds of persons treatment",
    "109": "Historical & collected persons treatment",
    "111": "Ontology",
    "113": "Cosmology",
    "114": "Space",
    "115": "Time",
    "116": "Change",
    "117": "Structure",
    "118": "Force & energy",
    "119": "Number & quantity",
    "121": "Epistemology",
    "122": "Causation",
    "123": "Determinism & indeterminism",
    "124": "Teleology",
    "126": "The self",
    "127": "The unconscious & the subconscious",
    "128": "Humankind",
    "129": "Origin & destiny of individual souls",
    "131": "Parapsychological & occult methods",
    "133": "Specific topics in parapsychology & occultism",
    "135": "Dreams & mysteries",
    "137": "Divinatory graphology",
    "138": "Physiognomy",
    "139": "Phrenology",
    "141": "Idealism & related systems",
    "142": "Critical philosophy",
    "143": "Bergsonism & intuitionism",
    "144": "Humanism & related systems",
    "145": "Sensationalism",
    "146": "Naturalism & related systems",
    "147": "Pantheism & related systems",
    "148": "Eclecticism, liberalism & traditionalism",
    "149": "Other philosophical systems",
    "152": "Perception, movement, emotions & drives",
    "153": "Mental processes & intelligence",
    "154": "Subconscious & altered states",
    "155": "Differential & developmental psychology",
    "156": "Comparative psychology",
    "158": "Applied psychology",
    "161": "Induction",
    "162": "Deduction",
    "165": "Fallacies & sources of error",
    "166": "Syllogisms",
    "167": "Hypotheses",
    "168": "Argument & persuasion",
    "169": "Analogy",
    "171": "Ethical systems",
    "172": "Political ethics",
    "173": "Ethics of family relationships",
    "174": "Occupational ethics",
    "175": "Ethics of recreation & leisure",
    "176": "Ethics of sex & reproduction",
    "177": "Ethics of social relations",
    "178": "Ethics of consumption",
    "179": "Other ethical norms",
    "181": "Eastern philosophy",
    "182": "Pre-Socratic Greek philosophies",
    "183": "Socratic & related philosophies",
    "184": "Platonic philosophy",
    "185": "Aristotelian philosophy",
    "186": "Skeptic & Neoplatonic philosophies",
    "187": "Epicurean philosophy",
    "188": "Stoic philosophy",
    "189": "Medieval western philosophy",
    "191": "Philosophy of United States & Canada",
    "192": "Philosophy of British Isles",
    "193": "Philosophy of Germany & Austria",
    "194": "Philosophy of France",
    "195": "Philosophy of Italy",
    "196": "Philosophy of Spain & Portugal",
    "197": "Philosophy of former Soviet Union",
    "198": "Philosophy of Scandinavia",
    "199": "Philosophy in other geographic areas",
    "201": "Religious mythology & social theology",
    "202": "Doctrines",
    "203": "Public worship & other practices",
    "204": "Religious experience, life & practice",
    "205": "Religious ethics",
    "206": "Leaders & organization",
    "207": "Missions & religious education",
    "208": "Sources",
    "209": "Sects & reform movements",
    "211": "Concepts of God",
    "212": "Existence, knowability & attributes of God",
    "213": "Creation",
    "214": "Theodicy",
    "215": "Science & religion",
    "218": "Humankind",
    "221": "Old Testament (Tanakh)",
    "222": "Historical books of Old Testament",
    "223": "Poetic books of Old Testament",
    "224": "Prophetic books of Old Testament",
    "225": "New Testament",
    "226": "Gospels & Acts",
    "227": "Epistles",
    "228": "Revelation (Apocalypse)",
    "229": "Apocrypha & pseudepigrapha",
    "231": "God",
    "232": "Jesus Christ & his family",
    "233": "Humankind",
    "234": "Salvation & grace",
    "235": "Spiritual beings",
    "236": "Eschatology",
    "238": "Creeds & catechisms",
    "239": "Apologetics & polemics",
    "241": "Christian ethics",
    "242": "Devotional literature",
    "243": "Evangelistic writings for individuals",
    "246": "Use of art in Christianity",
    "247": "Church furnishings & articles",
    "248": "Christian experience, practice & life",
    "249": "Christian observances in family life",
    "251": "Preaching",
    "252": "Texts of sermons",
    "253": "Pastoral office & work",
    "254": "Parish administration",
    "255": "Religious congregations & orders",
    "259": "Pastoral care of families & kinds of persons",
    "261": "Social theology",
    "262": "Ecclesiology",
    "263": "Days, times & places of observance",
    "264": "Public worship",
    "265": "Sacraments, other rites & acts",
    "266": "Missions",
    "267": "Associations for religious work",
    "268": "Religious education",
    "269": "Spiritual renewal",
    "271": "Religious orders in church history",
    "272": "Persecutions in church history",
    "273": "Doctrinal controversies & heresies",
    "274": "History of Christianity in Europe",
    "275": "History of Christianity in Asia",
    "276": "History of Christianity in Africa",
    "277": "History of Christianity in North America",
    "278": "History of Christianity in South America",
    "279": "History of Christianity in other areas",
    "281": "Early church & Eastern churches",
    "282": "Roman Catholic Church",
    "283": "Anglican churches",
    "284": "Protestants of Continental origin",
    "285": "Presbyterian, Reformed & Congregational",
    "286": "Baptist, Disciples of Christ & Adventist",
    "287": "Methodist & related churches",
    "289": "Other denominations & sects",
    "292": "Greek & Roman religion",
    "293": "Germanic religion",
    "294": "Religions of Indic origin",
    "295": "Zoroastrianism",
    "296": "Judaism",
    "297": "Islam, Babism & Bahai Faith",
    "298": "(Optional number)",
    "299": "Religions not provided for elsewhere",
    "301": "Sociology & anthropology",
    "302": "Social interaction",
    "303": "Social processes",
    "304": "Factors affecting social behavior",
    "305": "Social groups",
    "306": "Culture & institutions",
    "307": "Communities",
    "314": "General statistics of Europe",
    "315": "General statistics of Asia",
    "316": "General statistics of Africa",
    "317": "General statistics of North America",
    "318": "General statistics of South America",
    "319": "General statistics of other areas",
    "321": "Systems of governments & states",
    "322": "Relation of state to organized groups",
    "323": "Civil & political rights",
    "324": "The political process",
    "325": "International migration & colonization",
    "326": "Slavery & emancipation",
    "327": "International relations",
    "328": "The legislative process",
    "331": "Labor economics",
    "332": "Financial economics",
    "333": "Economics of land & energy",
    "334": "Cooperatives",
    "335": "Socialism & related systems",
    "336": "Public finance",
    "337": "International economics",
    "338": "Production",
    "339": "Macroeconomics & related topics",
    "341": "Law of nations",
    "342": "Constitutional & administrative law",
    "343": "Military, tax, trade & industrial law",
    "344": "Labor, social, education & cultural law",
    "345": "Criminal law",
    "346": "Private law",
    "347": "Civil procedure & courts",
    "348": "Laws, regulations & cases",
    "349": "Law of specific jurisdictions & areas",
    "351": "Public administration",
    "352": "General considerations of public administration",
    "353": "Specific fields of public administration",
    "354": "Administration of economy & environment",
    "355": "Military science",
    "356": "Infantry forces & warfare",
    "357": "Mounted forces & warfare",
    "358": "Air & other specialized forces",
    "359": "Sea forces & warfare",
    "361": "Social problems & social welfare in general",
    "362": "Social welfare problems & services",
    "363": "Other social problems & services",
    "364": "Criminology",
    "365": "Penal & related institutions",
    "366": "Associations",
    "367": "General clubs",
    "368": "Insurance",
    "369": "Miscellaneous kinds of associations",
    "371": "Schools & their activities; special education",
    "372": "Elementary education",
    "373": "Secondary education",
    "374": "Adult education",
    "375": "Curricula",
    "378": "Higher education",
    "379": "Public policy issues in education",
    "381": "Commerce",
    "382": "International commerce",
    "383": "Postal communication",
    "384": "Communications; telecommunication",
    "385": "Railroad transportation",
    "386": "Inland waterway & ferry transportation",
    "387": "Water, air & space transportation",
    "388": "Transportation; ground transportation",
    "389": "Metrology & standardization",
    "391": "Costume & personal appearance",
    "392": "Customs of life cycle & domestic life",
    "393": "Death customs",
    "394": "General customs",
    "395": "Etiquette (Manners)",
    "398": "Folklore",
    "399": "Customs of war & diplomacy",
    "401": "Philosophy & theory",
    "402": "Miscellany",
    "403": "Dictionaries & encyclopedias",
    "404": "Special topics",
    "405": "Serial publications",
    "406": "Organizations & management",
    "407": "Education, research & related topics",
    "408": "Kinds of persons treatment",
    "409": "Geographic & persons treatment",
    "411": "Writing systems",
    "412": "Etymology",
    "413": "Dictionaries",
    "414": "Phonology & phonetics",
    "415": "Grammar",
    "417": "Dialectology & historical linguistics",
    "418": "Standard usage & applied linguistics",
    "419": "Sign languages",
    "421": "English writing system & phonology",
    "422": "English etymology",
    "423": "English dictionaries",
    "425": "English grammar",
    "427": "English language variations",
    "428": "Standard English usage",
    "429": "Old English (Anglo-Saxon)",
    "431": "German writing systems & phonology",
    "432": "German etymology",
    "433": "German dictionaries",
    "435": "German grammar",
    "437": "German language variations",
    "438": "Standard German usage",
    "439": "Other Germanic languages",
    "441": "French writing systems & phonology",
    "442": "French etymology",
    "443": "French dictionaries",
    "445": "French grammar",
    "447": "French language variations",
    "448": "Standard French usage",
    "449": "Occitan & Catalan",
    "451": "Italian writing systems & phonology",
    "452": "Italian etymology",
    "453": "Italian dictionaries",
    "455": "Italian grammar",
    "457": "Italian language variations",
    "458": "Standard Italian usage",
    "459": "Romanian & related languages",
    "461": "Spanish writing systems & phonology",
    "462": "Spanish etymology",
    "463": "Spanish dictionaries",
    "465": "Spanish grammar",
    "467": "Spanish language variations",
    "468": "Standard Spanish usage",
    "469": "Portuguese",
    "471": "Classical Latin writing & phonology",
    "472": "Classical Latin etymology",
    "473": "Classical Latin dictionaries",
    "475": "Classical Latin grammar",
    "477": "Old, postclassical & Vulgar Latin",
    "478": "Classical Latin usage",
    "479": "Other Italic languages",
    "481": "Classical Greek writing & phonology",
    "482": "Classical Greek etymology",
    "483": "Classical Greek dictionaries",
    "485": "Classical Greek grammar",
    "487": "Preclassical & postclassical Greek",
    "488": "Classical Greek usage",
    "489": "Other Hellenic languages",
    "491": "East Indo-European & Celtic languages",
    "492": "Afro-Asiatic languages; Semitic languages",
    "493": "Non-Semitic Afro-Asiatic languages",
    "494": "Altaic, Uralic, Hyperborean & Dravidian",
    "495": "Languages of East & Southeast Asia",
    "496": "African languages",
    "497": "North American native languages",
    "498": "South American native languages",
    "499": "Austronesian & other languages",
    "501": "Philosophy & theory",
    "502": "Miscellany",
    "503": "Dictionaries & encyclopedias",
    "505": "Serial publications",
    "506": "Organizations & management",
    "507": "Education, research & related topics",
    "508": "Natural history",
    "509": "Historical, geographic & persons treatment",
    "511": "General principles of mathematics",
    "512": "Algebra",
    "513": "Arithmetic",
    "514": "Topology",
    "515": "Analysis",
    "516": "Geometry",
    "518": "Numerical analysis",
    "519": "Probabilities & applied mathematics",
    "521": "Celestial mechanics",
    "522": "Techniques, equipment & materials",
    "523": "Specific celestial bodies & phenomena",
    "525": "Earth (Astronomical geography)",
    "526": "Mathematical geography",
    "527": "Celestial navigation",
    "528": "Ephemerides",
    "529": "Chronology",
    "531": "Classical mechanics; solid mechanics",
    "532": "Fluid mechanics; liquid mechanics",
    "533": "Gas mechanics",
    "534": "Sound & related vibrations",
    "535": "Light & infrared & ultraviolet phenomena",
    "536": "Heat",
    "537": "Electricity & electronics",
    "538": "Magnetism",
    "539": "Modern physics",
    "541": "Physical chemistry",
    "542": "Techniques, equipment & materials",
    "543": "Analytical chemistry",
    "546": "Inorganic chemistry",
    "547": "Organic chemistry",
    "548": "Crystallography",
    "549": "Mineralogy",
    "551": "Geology, hydrology & meteorology",
    "552": "Petrology",
    "553": "Economic geology",
    "554": "Earth sciences of Europe",
    "555": "Earth sciences of Asia",
    "556": "Earth sciences of Africa",
    "557": "Earth sciences of North America",
    "558": "Earth sciences of South America",
    "559": "Earth sciences of other areas",
    "561": "Paleobotany; fossil microorganisms",
    "562": "Fossil invertebrates",
    "563": "Fossil marine & seashore invertebrates",
    "564": "Fossil mollusks & molluscoids",
    "565": "Fossil arthropods",
    "566": "Fossil chordates",
    "567": "Fossil cold-blooded vertebrates; fossil fishes",
    "568": "Fossil birds",
    "569": "Fossil mammals",
    "571": "Physiology & related subjects",
    "572": "Biochemistry",
    "573": "Specific physiological systems in animals",
    "575": "Specific parts of & systems in plants",
    "576": "Genetics & evolution",
    "577": "Ecology",
    "578": "Natural history of organisms",
    "579": "Microorganisms, fungi & algae",
    "581": "Specific topics in natural history",
    "582": "Plants noted for characteristics & flowers",
    "583": "Dicotyledons",
    "584": "Monocotyledons",
    "585": "Gymnosperms; conifers",
    "586": "Seedless plants",
    "587": "Vascular seedless plants",
    "588": "Bryophytes",
    "591": "Specific topics in natural history",
    "592": "Invertebrates",
    "593": "Marine & seashore invertebrates",
    "594": "Mollusks & molluscoids",
    "595": "Arthropods",
    "596": "Chordates",
    "597": "Cold-blooded vertebrates; fishes",
    "598": "Birds",
    "599": "Mammals",
    "601": "Philosophy & theory",
    "602": "Miscellany",
    "603": "Dictionaries & encyclopedias",
    "604": "Special topics",
    "605": "Serial publications",
    "606": "Organizations",
    "607": "Education, research & related topics",
    "608": "Inventions & patents",
    "609": "Historical, geographic & persons treatment",
    "611": "Human anatomy, cytology & histology",
    "612": "Human physiology",
    "613": "Personal health & safety",
    "614": "Incidence & prevention of disease",
    "615": "Pharmacology & therapeutics",
    "616": "Diseases",
    "617": "Surgery & related medical specialties",
    "618": "Gynecology, obstetrics, pediatrics & geriatrics",
    "621": "Applied physics",
    "622": "Mining & related operations",
    "623": "Military & nautical engineering",
    "624": "Civil engineering",
    "625": "Engineering of railroads & roads",
    "627": "Hydraulic engineering",
    "628": "Sanitary & municipal engineering",
    "629": "Other branches of engineering",
    "631": "Techniques, equipment & materials",
    "632": "Plant injuries, diseases & pests",
    "633": "Field & plantation crops",
    "634": "Orchards, fruits & forestry",
    "635": "Garden crops (Horticulture)",
    "636": "Animal husbandry",
    "637": "Processing dairy & related products",
    "638": "Insect culture",
    "639": "Hunting, fishing & conservation",
    "641": "Food & drink",
    "642": "Meals & table service",
    "643": "Housing & household equipment",
    "644": "Household utilities",
    "645": "Household furnishings",
    "646": "Sewing, clothing & personal living",
    "647": "Management of public households",
    "648": "Housekeeping",
    "649": "Child rearing & home care of persons",
    "651": "Office services",
    "652": "Processes of written communication",
    "653": "Shorthand",
    "657": "Accounting",
    "658": "General management",
    "659": "Advertising & public relations",
    "661": "Industrial chemicals",
    "662": "Explosives, fuels & related products",
    "663": "Beverage technology",
    "664": "Food technology",
    "665": "Industrial oils, fats, waxes & gases",
    "666": "Ceramic & allied technologies",
    "667": "Cleaning, color & coating technologies",
    "668": "Technology of other organic products",
    "669": "Metallurgy",
    "671": "Metalworking & primary metal products",
    "672": "Iron, steel & other iron alloys",
    "673": "Nonferrous metals",
    "674": "Lumber processing, wood products & cork",
    "675": "Leather & fur processing",
    "676": "Pulp & paper technology",
    "677": "Textiles",
    "678": "Elastomers & elastomer products",
    "679": "Other products of specific materials",
    "681": "Precision instruments & other devices",
    "682": "Small forge work (Blacksmithing)",
    "683": "Hardware & household appliances",
    "684": "Furnishings & home workshops",
    "685": "Leather, fur goods & related products",
  }
}