
# LOCAL CKAN DATA
# ***************
local_organization_data = {'approval_status': 'approved',
                                'created': '2021-07-22T14:33:24.825599',
                                'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                'display_name': 'TIB',
                                'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                'image_display_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'is_organization': True,
                                'name': 'tib-iasis',
                                'num_followers': 0,
                                'state': 'active',
                                'title': 'TIB',
                                'type': 'organization',
                                'tags': []}


local_dataset_data = {'author': 'Autodesk',
                      'author_email': '',
                      'creator_user_id': '6114fb41-d314-4c35-b8c1-278c9f997579',
                      'id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                      'isopen': True,
                      'license_id': 'cc-by',
                      'license_title': 'Creative Commons Attribution',
                      'license_url': 'http://www.opendefinition.org/licenses/cc-by',
                      'maintainer': '',
                      'maintainer_email': '',
                      'metadata_created': '2021-07-26T06:19:07.491127',
                      'metadata_modified': '2021-07-26T06:19:07.491139',
                      'name': 'example-cad',
                      'notes': 'Example usage of CAD visualization in 2D and 3D using CKAN Views.',
                      'num_resources': 2,
                      'num_tags': 0,
                      'organization': {'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                       'name': 'tib-iasis',
                                       'title': 'TIB',
                                       'type': 'organization',
                                       'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                       'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                       'created': '2021-07-22T14:33:24.825599',
                                       'is_organization': True,
                                       'approval_status': 'approved',
                                       'state': 'active'},
                      'owner_org': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                      'private': False,
                      'state': 'active',
                      'title': 'Example CAD',
                      'type': 'dataset',
                      'url': 'https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html',
                      'version': '',
                      'extras': [{'key': 'foobar', 'value': 'baz'}],
                      'resources': [{'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:37:19.897441',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '4ee0ec1c-c72b-4bad-be73-364a735cea5c',
                                     'last_modified': '2017-12-01T16:52:30.511835',
                                     'metadata_modified': '2021-07-26T05:23:45.398718',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 2D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 0,
                                     'resource_type': None,
                                     'size': 169807,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/Drive_shaft.dwg',
                                     'url_type': ''},
                                    {'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:40:23.217872',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '1342ec64-f18e-4860-93cc-f6dd194d56ec',
                                     'last_modified': '2017-12-01T16:53:23.693615',
                                     'metadata_modified': '2021-07-26T05:23:45.401967',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 3D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 1,
                                     'resource_type': None,
                                     'size': 733036,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/visualization_-_aerial.dwg',
                                     'url_type': ''}],
                      'tags': [],
                      'groups': [],
                      'relationships_as_subject': [],
                      'relationships_as_object': []}

# LUH API DATA
# ************

luh_api_package_list_no_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=package_list",
    "success": False,
    "error": {
        "message": "Not found",
        "__type": "Not Found Error"
    }
}

luh_api_package_list_with_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=package_list",
    "success": True,
    "result": [
        "a-generic-gust-definition-and-detection-method-based-on-wavelet-analysis",
        "a-neural-approach-for-text-extraction-from-scholarly-figures",
        "astrogeodetic-vertical-deflections-for-the-validation-of-gravity-field-models",
        "banker-plants-promote-biological-control-of-cabbage-whitefly",
        "beispiel-netzwerkmessdaten",
        "cho-2df",
        "cho-ir",
        "cho-stress-induced-product-production",
        "chrysanthemum-resistance-to-western-flower-thrips",
        "code-error-correction-properties-of-an-topological-insulator",
        "concrete-aggregate-benchmark",
        "condensates-of-so-5-_-n-anyons",
        "cotex-reflectance-and-eqe-measurements",
        "cov-19-img",
        "dataset-areas-with-low-and-medium-spatial-vulnerability-to-an-exemplary-prototype-wind-turbine-v1",
        "dataset-for-the-manuscript-ultracold-atom-interferometry-in-space",
        "dom2vec_pretrained",
        "electric-power-system-data-sets",
        "evaluation-of-the-palm-model-system-6-0-simulation-input-data-and-measurement-data",
        "finite-size-data-for-the-q-deformed-osp-3-2-superspin-chain",
        "first-nfdi4chem-user-survey",
        "genesis-and-features-of-dust-devil-like-vortices-in-turbulent-rayleigh-benard-convection",
        "global-pattern-search-for-alpha-level-optimisation",
        "gnss-mass-market-and-geodetic-receiver-benchmark-study",
        "gnss-measurement-data-on-the-urban-area-of-hildesheim",
        "gps-aided-camera-tracking-course",
        "gps-code-phase-variations-cpv",
        "gtem",
        "icsens-stereo-image-vehicle-dataset",
        "i-c-sens-visual-inertial-lidar-dataset",
        "ife10_2132",
        "image-text-classes",
        "importance-of-antixenosis-and-antibiosis-resistance-whitefly-brussels-sprouts",
        "importance-of-leaf-age-for-chrysanthemum-resistance-against-frankliniella-occidentalis",
        "iocw-image_description_templates",
        "isicom",
        "koesl-ergebnisse-geodaten_v1",
        "lastprofile-aus-trnsys-simulationen",
        "lastprofile-der-unterverteilung-des-gebaudes-1806-projektes-eltstore",
        "luh-grace2018",
        "luh-grace-fo-2020",
        "lumo",
        "matlab-simulink-files-mathematical-modeling-of-thyroid-homeostasis-implications-for-the-ahds",
        "mineral-intake-and-clinical-symptoms-in-adult-patients-with-hypophosphatasia-supplementary-material",
        "ml_household_end-use_load-profiles",
        "model-code-extended-code-and-job-setup-for-publication",
        "multi-view-pedestrian-tracking",
        "news400",
        "news-data-and-embeddings",
        "nlpcontributions-pilot-dataset",
        "oer-sample-data-set",
        "optimized-grid-planning-for-distribution-grids",
        "orkg-dils2018-use-case-dataset",
        "orkg-qa-table-dataset",
        "palm-6-0-r3668",
        "palm-6-0-r3921",
        "palm-6-0-r4093",
        "palm-6-0-revision-4508",
        "palm-6-0-revision-4564-mesoscale-nesting-interface-of-the-palm-model-system-6-0",
        "palm_land_surface_model",
        "reference-vibration-measurements-of-mensa-bridge-hannover",
        "rohdaten-fdm-umfrage",
        "role-of-cellular-architecture-in-protein-re-balancing-of-the-brassica-napus-embryo",
        "semeval-2021-task-11-shared-task-dataset",
        "simple-schlieren-imaging-setup-for-sound",
        "slideimages",
        "soil-moisture-measuring-campaign-ilmenau-2016-2017",
        "spectrum-of-so-7-_2-chain",
        "spin-noise-on-single-quantum-dot",
        "stem-ecr-v1-0",
        "stochastical-analysis-of-laser-tracker-at960-lr",
        "su2k-non-abelian-anyons-thermodynamics",
        "su3k-non-abelian-anyons-thermodynamics",
        "supplementary-data-dressieren-richten",
        "surface-roughness-of-real-operationally-used-compressor-blades",
        "tamperednews",
        "the-parallelized-large-eddy-simulation-model-palm-revision-2263",
        "towards-a-better-representation-of-fog-microphysics",
        "trajectories-in-a-shared-space",
        "trajectory-analysis-at-intersections-for-traffic-rule-identification",
        "trav-shacl-benchmarks-experimental-settings-and-evaluation",
        "urban-gnss-campaings-from-2015-2017-in-bad-frankenhausen-thuringia-from-simultan-project",
        "urban-gnss-campaings-from-2015-2017-in-hamburg-grob-flottbek-from-simultan-project",
        "user-code-job-setups-raw-data-plot-scripts-for-jgr-atmosphere",
        "vise",
        "wahc20",
        "wavelength-specific-behavior-of-the-western-flower-thrips",
        "windturbine-simulation-for-meta-modelling"
    ]
}

luh_api_package_show_no_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=package_show",
    "success": False,
    "error": {
        "message": "Not found",
        "__type": "Not Found Error"
    }
}

luh_api_package_show_with_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=package_show",
    "success": True,
    "result": {
        "domain": "https://data.uni-hannover.de",
        "license_title": "Creative Commons Attribution 3.0",
        "maintainer": "Helge Knoop",
        "relationships_as_object": [],
        "doi_status": True,
        "private": False,
        "maintainer_email": "knoop@muk.uni-hannover.de",
        "num_tags": 6,
        "id": "c76adf5a-9aa8-4ebe-bbbe-0e61436cf033",
        "metadata_created": "2019-07-09T17:21:22.824534",
        "metadata_modified": "2020-06-08T12:37:20.096728",
        "author": "Knoop, H., F. Ament, B. Maronga",
        "author_email": "knoop@muk.uni-hannover.de",
        "terms_of_usage": "Yes",
        "state": "active",
        "version": "",
        "creator_user_id": "c5b4da7a-1c07-4571-86fe-dbccdb3c0ed5",
        "type": "dataset",
        "have_copyright": "Yes",
        "num_resources": 2,
        "tags": [
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "Gusts",
                "id": "e4657ace-1f4a-41c9-9ea0-135ebe81bb30",
                "name": "Gusts"
            },
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "LES",
                "id": "128fad2a-257c-4571-a744-c4bd0a88f685",
                "name": "LES"
            },
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "LES model",
                "id": "7d220b59-627d-467d-bf15-74ff92258c09",
                "name": "LES model"
            },
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "Meteorology",
                "id": "0c4a0250-e82f-45d6-8459-b6b56db8c6b0",
                "name": "Meteorology"
            },
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "Wavelet Analysis",
                "id": "3e24f32a-2868-46b6-afac-2af9601df589",
                "name": "Wavelet Analysis"
            },
            {
                "vocabulary_id": None,
                "state": "active",
                "display_name": "large eddy simulation",
                "id": "8fac8fee-a2dc-4d9e-b614-87ff0eedda43",
                "name": "large eddy simulation"
            }
        ],
        "doi": "10.25835/0067988",
        "groups": [],
        "license_id": "CC-BY-3.0",
        "relationships_as_subject": [],
        "doi_publisher": "LUIS",
        "organization": {
            "description": "",
            "created": "2019-05-20T15:16:48.829339",
            "title": "AG PALM",
            "name": "ag-palm",
            "is_organization": True,
            "state": "active",
            "image_url": "",
            "revision_id": "c0beb04c-5579-4c9d-882f-2605932a351b",
            "type": "organization",
            "id": "2d2ca2a7-26f5-497b-b5a4-a559a28f3042",
            "approval_status": "approved"
        },
        "name": "a-generic-gust-definition-and-detection-method-based-on-wavelet-analysis",
        "isopen": True,
        "url": "",
        "notes": "This dataset is associated with the paper Knoop et al. (2019) titled  \"A generic gust definition and detection method based on wavelet-analysis\" published in \"Advances in Science and Research (ASR)\" within the Special Issue: 18th EMS Annual Meeting: European Conference for Applied Meteorology and Climatology 2018. It contains the data and analysis software required to recreate all figures in the publication.",
        "owner_org": "2d2ca2a7-26f5-497b-b5a4-a559a28f3042",
        "license_url": "https://creativecommons.org/licenses/by/3.0/",
        "resources": [
            {
                "mimetype": "application/zip",
                "cache_url": None,
                "hash": "",
                "description": "Wind velocity data in netCDF format, a python script for data analysis and a requirements.txt file containing all python package dependencies.",
                "name": "wavelet_gust_analysis.zip",
                "format": "ZIP",
                "url": "https://data.uni-hannover.de/dataset/c76adf5a-9aa8-4ebe-bbbe-0e61436cf033/resource/bd5d8d95-b3e2-4f25-a928-d75df8faf462/download/wavelet_gust_analysis.zip",
                "cache_last_updated": None,
                "package_id": "c76adf5a-9aa8-4ebe-bbbe-0e61436cf033",
                "created": "2019-07-09T17:27:20.908781",
                "state": "active",
                "mimetype_inner": None,
                "last_modified": "2019-07-09T17:27:20.810267",
                "position": 0,
                "revision_id": "d1eda8fb-3286-48e1-9795-ee78e56874f1",
                "url_type": "upload",
                "id": "bd5d8d95-b3e2-4f25-a928-d75df8faf462",
                "resource_type": None,
                "size": 96112
            },
            {
                "mimetype": "application/zip",
                "cache_url": None,
                "downloadall_datapackage_hash": "6cb014ee51e5610d5d066ae934214b3e",
                "hash": "",
                "description": "",
                "created": "2020-06-08T12:37:20.136795",
                "url": "https://data.uni-hannover.de/dataset/c76adf5a-9aa8-4ebe-bbbe-0e61436cf033/resource/8fa5e23c-6e72-486e-87f9-e16c75a38c4b/download/a-generic-gust-definition-and-detection-method-based-on-wavelet-analysis-duoest.zip",
                "format": "ZIP",
                "package_id": "c76adf5a-9aa8-4ebe-bbbe-0e61436cf033",
                "name": "All resource data",
                "cache_last_updated": None,
                "downloadall_metadata_modified": "2019-07-10T09:58:58.026541",
                "state": "active",
                "mimetype_inner": None,
                "last_modified": "2020-06-08T12:37:20.079983",
                "position": 1,
                "revision_id": "4f015311-bc6f-4514-a770-19b85ad6302b",
                "url_type": "upload",
                "id": "8fa5e23c-6e72-486e-87f9-e16c75a38c4b",
                "resource_type": None,
                "size": 86184
            }
        ],
        "title": "A generic gust definition and detection method based on wavelet-analysis",
        "revision_id": "cc07fb33-035d-432f-84f4-dc3b79795cd8",
        "doi_date_published": "2019-07-10"
    }
}

luh_api_organization_show_no_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=organization_show",
    "success": False,
    "error": {
        "message": "Not found",
        "__type": "Not Found Error"
    }
}

luh_api_organization_show_with_results = {
    "help": "https://data.uni-hannover.de/api/3/action/help_show?name=organization_show",
    "success": True,
    "result": {
        "users": [
            {
                "email_hash": "83479ff0e3addf6b81d204ae84f18d21",
                "about": None,
                "capacity": "editor",
                "name": "giersch-314",
                "created": "2019-05-20T15:17:21.315462",
                "sysadmin": False,
                "activity_streams_email_notifications": False,
                "state": "active",
                "number_of_edits": 66,
                "display_name": "giersch-314",
                "fullname": None,
                "id": "f23eac8f-a01f-409b-b92a-6affe3816569",
                "number_created_packages": 2
            },
            {
                "email_hash": "1804a5be6e115fcb2f7cf56b2a54fac1",
                "about": None,
                "capacity": "editor",
                "name": "maronga-3094",
                "created": "2019-10-22T12:57:47.468953",
                "sysadmin": False,
                "activity_streams_email_notifications": False,
                "state": "active",
                "number_of_edits": 18,
                "display_name": "maronga-3094",
                "fullname": None,
                "id": "db2d7200-1a69-4d69-885f-e3d46904a4b2",
                "number_created_packages": 3
            },
            {
                "email_hash": "a47d7e1cecb1b46dcde39bb005e77eef",
                "about": "CKANs DevOp @ LUIS",
                "capacity": "admin",
                "name": "reikokaps",
                "created": "2017-12-18T11:21:50.600406",
                "sysadmin": True,
                "activity_streams_email_notifications": True,
                "state": "active",
                "number_of_edits": 796,
                "display_name": "Reiko Kaps",
                "fullname": "Reiko Kaps",
                "id": "146127b1-d7ba-4873-b855-5dee0256fc5a",
                "number_created_packages": 2
            }
        ],
        "display_name": "AG PALM",
        "description": "",
        "image_display_url": "",
        "package_count": 9,
        "created": "2019-05-20T15:16:48.829339",
        "name": "ag-palm",
        "is_organization": True,
        "state": "active",
        "extras": [],
        "image_url": "",
        "groups": [
            {
                "capacity": "public",
                "name": "institut-fuer-meteorologie-und-klimatologie"
            }
        ],
        "type": "organization",
        "title": "AG PALM",
        "revision_id": "c0beb04c-5579-4c9d-882f-2605932a351b",
        "num_followers": 3,
        "id": "2d2ca2a7-26f5-497b-b5a4-a559a28f3042",
        "tags": [],
        "approval_status": "approved"
    }
}

luh_datasets_and_resources_keys =  {'dataset_keys':
                                        ['domain', 'license_title', 'maintainer', 'relationships_as_object',
                                         'doi_status', 'private', 'maintainer_email', 'num_tags',
                                         'id', 'metadata_created', 'metadata_modified', 'author',
                                         'author_email', 'terms_of_usage', 'state', 'version',
                                         'creator_user_id', 'type', 'have_copyright', 'num_resources',
                                         'tags', 'doi', 'groups', 'license_id', 'relationships_as_subject',
                                         'doi_publisher', 'organization', 'name', 'isopen', 'url', 'notes',
                                         'owner_org', 'license_url', 'resources', 'title', 'revision_id',
                                         'doi_date_published', 'repository_name', 'source_metadata_created',
                                         'source_metadata_modified', 'extras'],
                                    'resource_keys': ['mimetype', 'cache_url', 'hash', 'description',
                                                      'name', 'format', 'url', 'cache_last_updated',
                                                      'package_id', 'created', 'state', 'mimetype_inner',
                                                      'last_modified', 'position', 'revision_id',
                                                      'url_type', 'id', 'resource_type', 'size',
                                                      'downloadall_datapackage_hash',
                                                      'downloadall_metadata_modified']}

luh_resources_formats = ['ZIP', 'ASCII', 'CSV', 'TXT', 'JSON', 'XML',
                         '', 'PNG', '.csv', 'TAR', 'SHP', '.tiff', 'TIFF',
                         'tar.gz', 'PDF', 'matlab', 'video/mp4', 'JPEG', '7z',
                         'application/x-7z-compressed', 'obj', 'RAR', 'json, pdf, txt',
                         'XLSX', 'CSV, TXT', '.zip', 'GFC', 'chemical/x-gamess-input',
                         'XLS', 'video/quicktime', '.md', 'Turtle']