# LOCAL CKAN DATA
# ***************
local_organization_data = {'approval_status': 'approved',
                                'created': '2021-07-22T14:33:24.825599',
                                'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                'display_name': 'TIB',
                                'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                'image_display_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'is_organization': True,
                                'name': 'tib-iasis',
                                'num_followers': 0,
                                'state': 'active',
                                'title': 'TIB',
                                'type': 'organization',
                                'tags': []}


local_dataset_data = {'author': 'Autodesk',
                      'author_email': '',
                      'creator_user_id': '6114fb41-d314-4c35-b8c1-278c9f997579',
                      'id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                      'isopen': True,
                      'license_id': 'cc-by',
                      'license_title': 'Creative Commons Attribution',
                      'license_url': 'http://www.opendefinition.org/licenses/cc-by',
                      'maintainer': '',
                      'maintainer_email': '',
                      'metadata_created': '2021-07-26T06:19:07.491127',
                      'metadata_modified': '2021-07-26T06:19:07.491139',
                      'name': 'example-cad',
                      'notes': 'Example usage of CAD visualization in 2D and 3D using CKAN Views.',
                      'num_resources': 2,
                      'num_tags': 0,
                      'organization': {'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                       'name': 'tib-iasis',
                                       'title': 'TIB',
                                       'type': 'organization',
                                       'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                       'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                       'created': '2021-07-22T14:33:24.825599',
                                       'is_organization': True,
                                       'approval_status': 'approved',
                                       'state': 'active'},
                      'owner_org': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                      'private': False,
                      'state': 'active',
                      'title': 'Example CAD',
                      'type': 'dataset',
                      'url': 'https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html',
                      'version': '',
                      'extras': [{'key': 'foobar', 'value': 'baz'}],
                      'resources': [{'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:37:19.897441',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '4ee0ec1c-c72b-4bad-be73-364a735cea5c',
                                     'last_modified': '2017-12-01T16:52:30.511835',
                                     'metadata_modified': '2021-07-26T05:23:45.398718',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 2D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 0,
                                     'resource_type': None,
                                     'size': 169807,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/Drive_shaft.dwg',
                                     'url_type': ''},
                                    {'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:40:23.217872',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '1342ec64-f18e-4860-93cc-f6dd194d56ec',
                                     'last_modified': '2017-12-01T16:53:23.693615',
                                     'metadata_modified': '2021-07-26T05:23:45.401967',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 3D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 1,
                                     'resource_type': None,
                                     'size': 733036,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/visualization_-_aerial.dwg',
                                     'url_type': ''}],
                      'tags': [],
                      'groups': [],
                      'relationships_as_subject': [],
                      'relationships_as_object': []}

# GOETTINGEN API DATA
# ********************


goettingen_dataset_parsed_to_ckan_dict = {'repository_name': 'Göttingen Research Online Data', 
                                          'type': 'vdataset', 
                                          'source_metadata_created': '2021', 
                                          'source_metadata_modified': '', 
                                          'owner_org': 'goettingen', 
                                          'author': 'Khan, Sarah', 
                                          'author_email': '', 
                                          'doi': '10.25625/EDOTRQ', 
                                          'doi_date_published': '2021', 
                                          'doi_publisher': '', 
                                          'doi_status': 'True', 
                                          'isopen': True, 
                                          'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 
                                          'license_title': 'Creative Commons Zero (CC0)', 
                                          'name': 'goe-doi-10-25625-edotrq', 
                                          'notes': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY', 
                                          'organization': {'approval_status': 'approved', 
                                                           'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 
                                                           'display_name': 'GöttingenResearchOnline', 
                                                           'image_display_url': 'logo-goettingen.png', 
                                                           'image_url': 'logo-goettingen.png', 
                                                           'is_organization': True, 
                                                           'name': 'goettingen', 
                                                           'state': 'active', 
                                                           'title': 'GöttingenResearchOnline', 
                                                           'type': 'organization'}, 
                                            'title': 'Test2', 
                                            'url': 'https://doi.org/10.25625/EDOTRQ', 
                                            'citation': [], 
                                            'givenName': 'Sarah', 
                                            'familyName': 'Khan', 
                                            'orcid': '', 
                                            'publishers': [{'publisher': 'GRO.data'}], 
                                            'publication_year': '2021', 
                                            'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agricultural Sciences'}], 
                                            'resource_type': 'Dataset', 
                                            'related_identifiers': [{'identifier': 'http://fsi.nic.in/details.php?pgID=sb_64', 
                                                                     'identifier_type': 'URL', 
                                                                     'relation_type': 'IsPublishedIn', 
                                                                     'title': 'Government of India, Ministry of Environment, Forest and Climate Change [Internet]. Forest survey of India. [cited 2018 Apr 25] PONE-D-18-25176R1 (manuscript accepted for publication)'}], 
                                            'tags': [{'display_name': 'Social Sciences', 'name': 'Social Sciences', 'state': 'active', 'vocabulary_id': None}]}

LDM_imported_dataset = {"author": "Hoffmann, Ellen", 
                        "author_email": "", "citation": [], "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700", 
                        "doi": "10.25625/CMAYWL", 
                        "doi_date_published": "2019", 
                        "doi_publisher": "", 
                        "doi_status": "True", 
                        "familyName": "Hoffmann", 
                        "givenName": "Ellen", 
                        "id": "1080a0cc-b711-4cc1-9d22-a0887d5b1608", 
                        "isopen": True, 
                        "license_id": "http://creativecommons.org/publicdomain/zero/1.0", 
                        "license_title": "http://creativecommons.org/publicdomain/zero/1.0", 
                        "metadata_created": "2025-04-30T06:09:57.448871", 
                        "metadata_modified": "2025-04-30T06:21:17.206135", 
                        "name": "goe-doi-10-25625-cmaywl", 
                        "notes": "Forest survey of India - Data retrieved for forest cover analysis at district, state, and national level", 
                        "num_resources": 0, 
                        "num_tags": 1, 
                        "orcid": "", 
                        "organization": {"id": "18dd149c-a13c-4c67-bad7-b00fdcfd46a4", 
                                         "name": "goettingen", 
                                         "title": "G\u00f6ttingenResearchOnline", 
                                         "type": "organization", 
                                         "description": "G\u00f6ttingen Research Online is an institutional repository for the publication of research data at the G\u00f6ttingen Campus. It is managed by the G\u00f6ttingen eResearch Alliance, a joint group of SUB and GWDG. .", "image_url": "logo-goettingen.png", "created": "2025-04-30T07:58:44.287190", "is_organization": True, "approval_status": "approved", "state": "active"}, 
                                         "owner_org": "18dd149c-a13c-4c67-bad7-b00fdcfd46a4", 
                                         "private": False, 
                                         "publication_year": "2019", 
                                         "repository_name": "G\u00f6ttingen Research Online Data", 
                                         "resource_type": "Dataset", 
                                         "source_metadata_created": "2019", 
                                         "source_metadata_modified": "", 
                                         "state": "active", 
                                         "title": "Forest-survey_excerpt", 
                                         "type": "vdataset", 
                                         "url": "https://doi.org/10.25625/CMAYWL", 
                                         "publishers": [{"publisher": "GRO.data"}], 
                                         "tags": [{"display_name": "Agricultural Sciences", "id": "ecc84589-c451-48bc-9ddc-4db82f487962", "name": "Agricultural Sciences", "state": "active", "vocabulary_id": None}], "resources": [], "groups": [], "relationships_as_subject": [], "relationships_as_object": [], "services_used_list": ""}

resumption_token_ok = {'resumptionToken': 'rows=100@@searchMark=10.22000/72@@from=0001-01-01T00:00:00Z@@total=179@@until=9999-12-31T23:59:59Z@@metadataPrefix=radar', 'completeListSize': '179'}

resumption_token_empty = {'resumptionToken': ''}

expected_list_of_dict_from_goettingen = [{'@context': 'http://schema.org', '@type': 'Dataset', '@id': 'https://doi.org/10.25625/EDOTRQ', 'identifier': 'https://doi.org/10.25625/EDOTRQ', 'name': 'Test2', 'creator': [{'@type': 'Person', 'givenName': 'Sarah', 'familyName': 'Khan', 'name': 'Khan, Sarah'}], 'author': [{'@type': 'Person', 'givenName': 'Sarah', 'familyName': 'Khan', 'name': 'Khan, Sarah'}], 'datePublished': '2021-03-08', 'dateModified': '2021-03-08', 'version': '1', 'description': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY', 'keywords': ['Social Sciences'], 'license': 'http://creativecommons.org/publicdomain/zero/1.0', 'includedInDataCatalog': {'@type': 'DataCatalog', 'name': 'GRO.data', 'url': 'https://data.goettingen-research-online.de'}, 'publisher': {'@type': 'Organization', 'name': 'GRO.data'}, 'provider': {'@type': 'Organization', 'name': 'GRO.data'}, 'license_title': 'Creative Commons Zero (CC0)', 'subjects': ['Agricultural Sciences'], 'publications': [{'citation': 'Government of India, Ministry of Environment, Forest and Climate Change [Internet]. Forest survey of India. [cited 2018 Apr 25] PONE-D-18-25176R1 (manuscript accepted for publication)', 'url': 'http://fsi.nic.in/details.php?pgID=sb_64'}]}, {'@context': 'http://schema.org', '@type': 'Dataset', '@id': 'https://doi.org/10.25625/EDOTRQ', 'identifier': 'https://doi.org/10.25625/EDOTRQ', 'name': 'Test2', 'creator': [{'@type': 'Person', 'givenName': 'Sarah', 'familyName': 'Khan', 'name': 'Khan, Sarah'}], 'author': [{'@type': 'Person', 'givenName': 'Sarah', 'familyName': 'Khan', 'name': 'Khan, Sarah'}], 'datePublished': '2021-03-08', 'dateModified': '2021-03-08', 'version': '1', 'description': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY', 'keywords': ['Social Sciences'], 'license': 'http://creativecommons.org/publicdomain/zero/1.0', 'includedInDataCatalog': {'@type': 'DataCatalog', 'name': 'GRO.data', 'url': 'https://data.goettingen-research-online.de'}, 'publisher': {'@type': 'Organization', 'name': 'GRO.data'}, 'provider': {'@type': 'Organization', 'name': 'GRO.data'}, 'license_title': 'Creative Commons Zero (CC0)', 'subjects': ['Social Sciences'], 'publications': [{}]}, {'@context': 'http://schema.org', '@type': 'Dataset', '@id': 'https://doi.org/10.25625/2ZY9YD', 'identifier': 'https://doi.org/10.25625/2ZY9YD', 'name': 'Test 2', 'creator': [{'@type': 'Person', 'givenName': 'Thomas', 'familyName': 'Fischer', 'name': 'Thomas Fischer'}], 'author': [{'@type': 'Person', 'givenName': 'Thomas', 'familyName': 'Fischer', 'name': 'Thomas Fischer'}], 'datePublished': '2021-07-08', 'dateModified': '2021-07-08', 'version': '1', 'description': 'NA', 'keywords': ['Other', 'Testeingabe', 'zweites Schlagwort; drittes Schlagwort'], 'license': 'http://creativecommons.org/publicdomain/zero/1.0', 'includedInDataCatalog': {'@type': 'DataCatalog', 'name': 'GRO.data', 'url': 'https://data.goettingen-research-online.de'}, 'publisher': {'@type': 'Organization', 'name': 'GRO.data'}, 'provider': {'@type': 'Organization', 'name': 'GRO.data'}, 'license_title': 'Creative Commons Zero (CC0)', 'subjects': ['Other']}, {'@context': 'http://schema.org', '@type': 'Dataset', '@id': 'https://doi.org/10.25625/1V87BH', 'identifier': 'https://doi.org/10.25625/1V87BH', 'name': 'BExIS Source Code', 'creator': [{'@type': 'Person', 'givenName': 'Tim', 'familyName': 'Ritter', 'name': 'Tim Ritter'}], 'author': [{'@type': 'Person', 'givenName': 'Tim', 'familyName': 'Ritter', 'name': 'Tim Ritter'}], 'datePublished': '2021-07-08', 'dateModified': '2021-07-08', 'version': '1', 'description': 'na', 'keywords': ['Other', 'BExIS', 'Source Code'], 'license': 'http://creativecommons.org/publicdomain/zero/1.0', 'includedInDataCatalog': {'@type': 'DataCatalog', 'name': 'GRO.data', 'url': 'https://data.goettingen-research-online.de'}, 'publisher': {'@type': 'Organization', 'name': 'GRO.data'}, 'provider': {'@type': 'Organization', 'name': 'GRO.data'}, 'license_title': 'Creative Commons Zero (CC0)', 'subjects': ['Other']}, {'@context': 'http://schema.org', '@type': 'Dataset', '@id': 'https://doi.org/10.25625/DPGLRH', 'identifier': 'https://doi.org/10.25625/DPGLRH', 'name': 'Legal Document Test', 'creator': [{'@type': 'Person', 'givenName': 'Thomas', 'familyName': 'Fischer', 'name': 'Thomas Fischer'}], 'author': [{'@type': 'Person', 'givenName': 'Thomas', 'familyName': 'Fischer', 'name': 'Thomas Fischer'}], 'datePublished': '2021-07-08', 'dateModified': '2021-07-08', 'version': '1', 'description': 'na', 'keywords': ['Other', 'Legal documents'], 'license': 'http://creativecommons.org/publicdomain/zero/1.0', 'includedInDataCatalog': {'@type': 'DataCatalog', 'name': 'GRO.data', 'url': 'https://data.goettingen-research-online.de'}, 'publisher': {'@type': 'Organization', 'name': 'GRO.data'}, 'provider': {'@type': 'Organization', 'name': 'GRO.data'}, 'license_title': 'Creative Commons Zero (CC0)', 'subjects': ['Other']}]
goettingen_all_datasets_list_response = [{'repository_name': 'Göttingen Research Online Data', 'type': 'vdataset', 'source_metadata_created': '2021', 'source_metadata_modified': '', 'owner_org': 'goettingen', 'author': 'Khan, Sarah', 'author_email': '', 'doi': '10.25625/EDOTRQ', 'doi_date_published': '2021', 'doi_publisher': '', 'doi_status': 'True', 'isopen': True, 'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 'license_title': 'Creative Commons Zero (CC0)', 'name': 'goe-doi-10-25625-edotrq', 'notes': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY', 'organization': {'approval_status': 'approved', 'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 'display_name': 'GöttingenResearchOnline', 'image_display_url': 'logo-goettingen.png', 'image_url': 'logo-goettingen.png', 'is_organization': True, 'name': 'goettingen', 'state': 'active', 'title': 'GöttingenResearchOnline', 'type': 'organization'}, 'title': 'Test2', 'url': 'https://doi.org/10.25625/EDOTRQ', 'citation': [], 'givenName': 'Sarah', 'familyName': 'Khan', 'orcid': '', 'publishers': [{'publisher': 'GRO.data'}], 'publication_year': '2021', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agricultural Sciences'}], 'resource_type': 'Dataset', 'related_identifiers': [{'identifier': 'http://fsi.nic.in/details.php?pgID=sb_64', 'identifier_type': 'URL', 'relation_type': 'IsPublishedIn', 'title': 'Government of India, Ministry of Environment, Forest and Climate Change [Internet]. Forest survey of India. [cited 2018 Apr 25] PONE-D-18-25176R1 (manuscript accepted for publication)'}], 'tags': [{'display_name': 'Social Sciences', 'name': 'Social Sciences', 'state': 'active', 'vocabulary_id': None}]}, {'repository_name': 'Göttingen Research Online Data', 'type': 'vdataset', 'source_metadata_created': '2021', 'source_metadata_modified': '', 'owner_org': 'goettingen', 'author': 'Khan, Sarah', 'author_email': '', 'doi': '10.25625/EDOTRQ', 'doi_date_published': '2021', 'doi_publisher': '', 'doi_status': 'True', 'isopen': True, 'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 'license_title': 'Creative Commons Zero (CC0)', 'name': 'goe-doi-10-25625-edotrq', 'notes': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY', 'organization': {'approval_status': 'approved', 'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 'display_name': 'GöttingenResearchOnline', 'image_display_url': 'logo-goettingen.png', 'image_url': 'logo-goettingen.png', 'is_organization': True, 'name': 'goettingen', 'state': 'active', 'title': 'GöttingenResearchOnline', 'type': 'organization'}, 'title': 'Test2', 'url': 'https://doi.org/10.25625/EDOTRQ', 'citation': [], 'givenName': 'Sarah', 'familyName': 'Khan', 'orcid': '', 'publishers': [{'publisher': 'GRO.data'}], 'publication_year': '2021', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Social Sciences'}], 'resource_type': 'Dataset', 'related_identifiers': [{'identifier': '', 'identifier_type': 'URL', 'relation_type': 'IsPublishedIn', 'title': ''}]}, {'repository_name': 'Göttingen Research Online Data', 'type': 'vdataset', 'source_metadata_created': '2021', 'source_metadata_modified': '', 'owner_org': 'goettingen', 'author': 'Thomas Fischer', 'author_email': '', 'doi': '10.25625/2ZY9YD', 'doi_date_published': '2021', 'doi_publisher': '', 'doi_status': 'True', 'isopen': True, 'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 'license_title': 'Creative Commons Zero (CC0)', 'name': 'goe-doi-10-25625-2zy9yd', 'notes': 'NA', 'organization': {'approval_status': 'approved', 'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 'display_name': 'GöttingenResearchOnline', 'image_display_url': 'logo-goettingen.png', 'image_url': 'logo-goettingen.png', 'is_organization': True, 'name': 'goettingen', 'state': 'active', 'title': 'GöttingenResearchOnline', 'type': 'organization'}, 'title': 'Test 2', 'url': 'https://doi.org/10.25625/2ZY9YD', 'citation': [], 'givenName': 'Thomas', 'familyName': 'Fischer', 'orcid': '', 'publishers': [{'publisher': 'GRO.data'}], 'publication_year': '2021', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Other'}], 'resource_type': 'Dataset', 'tags': [{'display_name': 'Testeingabe', 'name': 'Testeingabe', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'zweites Schlagwort', 'name': 'zweites Schlagwort', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'drittes Schlagwort', 'name': 'drittes Schlagwort', 'state': 'active', 'vocabulary_id': None}]}, {'repository_name': 'Göttingen Research Online Data', 'type': 'vdataset', 'source_metadata_created': '2021', 'source_metadata_modified': '', 'owner_org': 'goettingen', 'author': 'Tim Ritter', 'author_email': '', 'doi': '10.25625/1V87BH', 'doi_date_published': '2021', 'doi_publisher': '', 'doi_status': 'True', 'isopen': True, 'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 'license_title': 'Creative Commons Zero (CC0)', 'name': 'goe-doi-10-25625-1v87bh', 'notes': 'na', 'organization': {'approval_status': 'approved', 'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 'display_name': 'GöttingenResearchOnline', 'image_display_url': 'logo-goettingen.png', 'image_url': 'logo-goettingen.png', 'is_organization': True, 'name': 'goettingen', 'state': 'active', 'title': 'GöttingenResearchOnline', 'type': 'organization'}, 'title': 'Bexis source code', 'url': 'https://doi.org/10.25625/1V87BH', 'citation': [], 'givenName': 'Tim', 'familyName': 'Ritter', 'orcid': '', 'publishers': [{'publisher': 'GRO.data'}], 'publication_year': '2021', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Other'}], 'resource_type': 'Dataset', 'tags': [{'display_name': 'BExIS', 'name': 'BExIS', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'Source Code', 'name': 'Source Code', 'state': 'active', 'vocabulary_id': None}]}, {'repository_name': 'Göttingen Research Online Data', 'type': 'vdataset', 'source_metadata_created': '2021', 'source_metadata_modified': '', 'owner_org': 'goettingen', 'author': 'Thomas Fischer', 'author_email': '', 'doi': '10.25625/DPGLRH', 'doi_date_published': '2021', 'doi_publisher': '', 'doi_status': 'True', 'isopen': True, 'license_id': 'http://creativecommons.org/publicdomain/zero/1.0', 'license_title': 'Creative Commons Zero (CC0)', 'name': 'goe-doi-10-25625-dpglrh', 'notes': 'na', 'organization': {'approval_status': 'approved', 'description': 'Göttingen Research Online is an institutional repository for the publication of research data at the Göttingen Campus. It is managed by the Göttingen eResearch Alliance, a joint group of SUB and GWDG. .', 'display_name': 'GöttingenResearchOnline', 'image_display_url': 'logo-goettingen.png', 'image_url': 'logo-goettingen.png', 'is_organization': True, 'name': 'goettingen', 'state': 'active', 'title': 'GöttingenResearchOnline', 'type': 'organization'}, 'title': 'Legal document test', 'url': 'https://doi.org/10.25625/DPGLRH', 'citation': [], 'givenName': 'Thomas', 'familyName': 'Fischer', 'orcid': '', 'publishers': [{'publisher': 'GRO.data'}], 'publication_year': '2021', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Other'}], 'resource_type': 'Dataset', 'tags': [{'display_name': 'Legal documents', 'name': 'Legal documents', 'state': 'active', 'vocabulary_id': None}]}]
goettingen_dataset_parsed_to_dict = expected_list_of_dict_from_goettingen[0]

ckan_dict_of_imported_dataset = {"author": "Khan, Sarah", 
                                 "author_email": "", 
                                 "citation": [], 
                                 "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700", 
                                 "doi": "10.25625/EDOTRQ", 
                                 "doi_date_published": "2021", 
                                 "doi_publisher": "", 
                                 "doi_status": "True", 
                                 "familyName": "Khan", 
                                 "givenName": "Sarah", 
                                 "id": "dcda00d0-6aaa-455a-a379-61a28ddc3c57", 
                                 "isopen": False, 
                                 "license_id": "http://creativecommons.org/publicdomain/zero/1.0", 
                                 "license_title": "http://creativecommons.org/publicdomain/zero/1.0", 
                                 "metadata_created": "2025-04-30T06:09:57.931695", 
                                 "metadata_modified": "2025-04-30T07:00:12.859589", 
                                 "name": "goe-doi-10-25625-edotrq", 
                                 "notes": "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JWMCXY", 
                                 "num_resources": 0, 
                                 "num_tags": 1, 
                                 "orcid": "", 
                                 "organization": {"id": "18dd149c-a13c-4c67-bad7-b00fdcfd46a4", 
                                                  "name": "goettingen", 
                                                  "title": "G\u00f6ttingenResearchOnline", 
                                                  "type": "organization", 
                                                  "description": "G\u00f6ttingen Research Online is an institutional repository for the publication of research data at the G\u00f6ttingen Campus. It is managed by the G\u00f6ttingen eResearch Alliance, a joint group of SUB and GWDG. .", 
                                                  "image_url": "logo-goettingen.png", 
                                                  "created": "2025-04-30T07:58:44.287190", 
                                                  "is_organization": True,
                                                  "approval_status": "approved", 
                                                  "state": "active"}, 
                                 "owner_org": "18dd149c-a13c-4c67-bad7-b00fdcfd46a4", 
                                 "private": False, 
                                 "publication_year": "2021", 
                                 "repository_name": "G\u00f6ttingen Research Online Data", 
                                 "resource_type": "Dataset", 
                                 "source_metadata_created": "2021", 
                                 "source_metadata_modified": "", 
                                 "state": "active", 
                                 "title": "Test2", 
                                 "type": "vdataset", 
                                 "url": "https://doi.org/10.25625/EDOTRQ", 
                                 "publishers": [{"publisher": "GRO.data"}], 
                                 "tags": [{"display_name": "Social Sciences", "id": "5a304755-86f0-4efd-928d-7ac7fe25f325", "name": "Social Sciences", "state": "active", "vocabulary_id": None}], 
                                 "resources": [], "groups": [], "relationships_as_subject": [], "relationships_as_object": [], "services_used_list": ""}




goettingen_dict_of_imported_dataset = goettingen_all_datasets_list_response[0]