# LOCAL CKAN DATA
# ***************
local_organization_data = {'approval_status': 'approved',
                                'created': '2021-07-22T14:33:24.825599',
                                'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                'display_name': 'TIB',
                                'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                'image_display_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'is_organization': True,
                                'name': 'tib-iasis',
                                'num_followers': 0,
                                'state': 'active',
                                'title': 'TIB',
                                'type': 'organization',
                                'tags': []}


local_dataset_data = {'author': 'Autodesk',
                      'author_email': '',
                      'creator_user_id': '6114fb41-d314-4c35-b8c1-278c9f997579',
                      'id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                      'isopen': True,
                      'license_id': 'cc-by',
                      'license_title': 'Creative Commons Attribution',
                      'license_url': 'http://www.opendefinition.org/licenses/cc-by',
                      'maintainer': '',
                      'maintainer_email': '',
                      'metadata_created': '2021-07-26T06:19:07.491127',
                      'metadata_modified': '2021-07-26T06:19:07.491139',
                      'name': 'example-cad',
                      'notes': 'Example usage of CAD visualization in 2D and 3D using CKAN Views.',
                      'num_resources': 2,
                      'num_tags': 0,
                      'organization': {'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                       'name': 'tib-iasis',
                                       'title': 'TIB',
                                       'type': 'organization',
                                       'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                       'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                       'created': '2021-07-22T14:33:24.825599',
                                       'is_organization': True,
                                       'approval_status': 'approved',
                                       'state': 'active'},
                      'owner_org': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                      'private': False,
                      'state': 'active',
                      'title': 'Example CAD',
                      'type': 'dataset',
                      'url': 'https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html',
                      'version': '',
                      'extras': [{'key': 'foobar', 'value': 'baz'}],
                      'resources': [{'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:37:19.897441',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '4ee0ec1c-c72b-4bad-be73-364a735cea5c',
                                     'last_modified': '2017-12-01T16:52:30.511835',
                                     'metadata_modified': '2021-07-26T05:23:45.398718',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 2D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 0,
                                     'resource_type': None,
                                     'size': 169807,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/Drive_shaft.dwg',
                                     'url_type': ''},
                                    {'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:40:23.217872',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '1342ec64-f18e-4860-93cc-f6dd194d56ec',
                                     'last_modified': '2017-12-01T16:53:23.693615',
                                     'metadata_modified': '2021-07-26T05:23:45.401967',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 3D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 1,
                                     'resource_type': None,
                                     'size': 733036,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/visualization_-_aerial.dwg',
                                     'url_type': ''}],
                      'tags': [],
                      'groups': [],
                      'relationships_as_subject': [],
                      'relationships_as_object': []}

# LEOPARD API DATA
# ***************


osnadata_dataset_parsed_to_dict = {'header': {'identifier': 'doi:10.26249/FK2/48FTWW', 
                                              'datestamp': '2024-07-12T00:00:00Z'}, 
                                              'metadata': {'osnaDataDataset': {'identifier': '10.26249/FK2/48FTWW', 
                                                                               'identifierType': 'DOI', 
                                                                               'creators': [{'creator': {'creatorName': {'creatorName': 'Margheritis, Eleonora Germana', 
                                                                                                                         'nameType': 'Personal'}, 
                                                                                                                         'givenName': 'Eleonora Germana', 
                                                                                                                         'familyName': 'Margheritis', 
                                                                                                                         'nameIdentifier': {'nameIdentifier': '0000-0003-0571-3563', 
                                                                                                                                            'nameIdentifierScheme': 'ORCID'}}}, 
                                                                                            {'creator': {'creatorName': {'creatorName': 'Cosentino, Katia', 
                                                                                                                         'nameType': 'Personal'}, 
                                                                                                                         'givenName': 'Katia', 
                                                                                                                         'familyName': 'Cosentino', 
                                                                                                                         'nameIdentifier': {'nameIdentifier': '0000-0002-3796-3500', 
                                                                                                                                            'nameIdentifierScheme': 'ORCID'}}}], 
                                                                                'titles': [{'title': {'title': 'Cooperativity of cysteines governs GSDMD palmitoylation-mediated membrane targeting and assembly'}}], 
                                                                                'publisher': 'osnaData', 
                                                                                'publicationYear': '2024', 
                                                                                'subjectAreas': [{'subject': {'subject': 'Medicine, Health and Life Sciences'}}], 
                                                                                'resourceType': {'resourceType': None, 'resourceTypeGeneral': 'Dataset'}, 
                                                                                'rightsList': [{'rights': {'rights': {'rights': None, 'rightsURI': 'info:eu-repo/semantics/openAccess'}}}], 
                                                                                'descriptions': [{'description': {'description': 'Gasdermin D (GSDMD) executes cell death program pyroptosis by assembling into oligomers that permeabilize the plasma membrane. Here, by single-molecule imaging, we elucidate the yet elusive mechanism of GSDMD pore assembly and the role of cysteines in GSDMD oligomerization. We show that GSDMD preassembles at the membrane into dimeric and trimeric building blocks that can either insert the membrane or further assemble into higher-order oligomers, prior to membrane insertion. Cys39, Cys57, and Cys192 are the only relevant cysteines in GSDMD oligomerization. S-palmitoylation of Cys192 controls GSDMD membrane targeting together with negatively charged lipids. Importantly, simultaneous Cys39/57/192-to-Ala mutations, but not Cys192 or the Cys39/57 pair individually, completely abolish GSDMD insertion into artificial membranes and the plasma membrane in cells. Finally, either Cys192 or the Cys39/Cys57 pair are sufficient to form dimers/trimers, but they are all required for functional higher-order oligomer formation. Overall, our study unveils a cooperative role of Cys192 palmitoylation-mediated membrane binding and Cys39/57/192-mediated oligomerization in GSDMD pore assembly. This study supports a model where GSDMD oligomerization relies on a two-step mechanism mediated by cysteines.\nRaw and Source data can be accessed via the link.'}, 
                                                                                                  'descriptionType': 'Abstract'}], 
                                                                                'keywords': [], 
                                                                                'contributors': [{'contributor': {'contributorName': {'contributorName': 'Margheritis, Eleonora Germana', 
                                                                                                                                      'nameType': 'Personal'}, 
                                                                                                                                      'givenName': 'Eleonora Germana', 
                                                                                                                                      'familyName': 'Margheritis', 
                                                                                                                                      'affiliation': 'Department of Biology/Chemistry and Center for Cellular Nanoanalytics (CellNanOs), University of Osnabrück, Germany'}}, 
                                                                                                {'contributor': {'contributorName': {'contributorName': 'Cosentino, Katia', 
                                                                                                                                     'nameType': 'Personal'}, 
                                                                                                                                     'givenName': 'Katia', 
                                                                                                                                     'familyName': 'Cosentino', 
                                                                                                                                     'affiliation': 'Department of Biology/Chemistry and Center for Cellular Nanoanalytics (CellNanOs), University of Osnabrück, Germany'}}], 
                                                                                'language': {}, 
                                                                                'alternateIdentifiers': [], 
                                                                                'relatedIdentifiers': [{'relatedIdentifier': {'relatedIdentifier': '10.17632/zdh4d5ws2z.2'}, 
                                                                                                        'relationType': 'IsCitedBy', 
                                                                                                        'relatedIdentifierType': 'DOI'}, 
                                                                                {'relatedIdentifier': {'relatedIdentifier': '10.1016/j.neunet.2020.11.004'}, 
                                                                                                        'relationType': 'IsCitedBy', 
                                                                                                        'relatedIdentifierType': 'DOI'}]}}}

osnadata_dataset_parsed_to_ckan_dict = {'repository_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 
                                        'type': 'vdataset', 
                                        'source_metadata_created': '2024', 
                                        'source_metadata_modified': '', 
                                        'owner_org': 'osnadata', 
                                        'author': 'Margheritis, Eleonora Germana', 
                                        'author_email': '', 
                                        'doi': '10.26249/FK2/48FTWW', 
                                        'doi_date_published': '2024', 
                                        'doi_publisher': '', 
                                        'doi_status': 'True', 
                                        'license_id': '', 
                                        'license_title': None, 
                                        'name': 'osn-doi-10-26249-fk2-48ftww', 
                                        'notes': 'Abstract: Gasdermin D (GSDMD) executes cell death program pyroptosis by assembling into oligomers that permeabilize the plasma membrane. Here, by single-molecule imaging, we elucidate the yet elusive mechanism of GSDMD pore assembly and the role of cysteines in GSDMD oligomerization. We show that GSDMD preassembles at the membrane into dimeric and trimeric building blocks that can either insert the membrane or further assemble into higher-order oligomers, prior to membrane insertion. Cys39, Cys57, and Cys192 are the only relevant cysteines in GSDMD oligomerization. S-palmitoylation of Cys192 controls GSDMD membrane targeting together with negatively charged lipids. Importantly, simultaneous Cys39/57/192-to-Ala mutations, but not Cys192 or the Cys39/57 pair individually, completely abolish GSDMD insertion into artificial membranes and the plasma membrane in cells. Finally, either Cys192 or the Cys39/Cys57 pair are sufficient to form dimers/trimers, but they are all required for functional higher-order oligomer formation. Overall, our study unveils a cooperative role of Cys192 palmitoylation-mediated membrane binding and Cys39/57/192-mediated oligomerization in GSDMD pore assembly. This study supports a model where GSDMD oligomerization relies on a two-step mechanism mediated by cysteines.\nRaw and Source data can be accessed via the link.', 
                                        'organization': {'approval_status': 'approved', 
                                                         'description': 'The Research Data Repository of the Osnabrück University.', 
                                                         'display_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 
                                                         'image_display_url': 'logo-osnaData.png', 
                                                         'image_url': 'logo-osnaData.png', 
                                                         'is_organization': True, 
                                                         'name': 'osnadata', 
                                                         'state': 'active', 
                                                         'title': 'osnaData (The Research Data Repository of the Osnabrück University)', 
                                                         'type': 'organization'}, 
                                        'title': 'Cooperativity of cysteines governs gsdmd palmitoylation-mediated membrane targeting and assembly', 
                                        'url': 'https://doi.org/10.26249/FK2/48FTWW', 
                                        'citation': [], 
                                        'givenName': 'Eleonora Germana', 
                                        'familyName': 'Margheritis', 
                                        'orcid': '0000-0003-0571-3563', 
                                        'extra_authors': [{'extra_author': 'Cosentino, Katia', 
                                                           'givenName': 'Katia', 
                                                           'familyName': 'Cosentino', 
                                                           'orcid': '0000-0002-3796-3500'}], 
                                        'publication_year': '2024', 
                                        'subject_areas': [{'subject_area_additional': '', 
                                                           'subject_area_name': 'Medicine, Health and Life Sciences'}], 
                                        'resource_type': 'Dataset', 
                                        'related_identifiers': [{'identifier': '10.17632/zdh4d5ws2z.2', 
                                                                 'identifier_type': 'DOI', 
                                                                 'relation_type': 'IsCitedBy'}, 
                                                                 {'identifier': '10.1016/j.neunet.2020.11.004', 
                                                                  'identifier_type': 'DOI', 
                                                                  'relation_type': 'IsCitedBy'}]}

LDM_imported_dataset = {
        "author": "Clemens Huebler",
        "author_email": "c.huebler@isd.uni-hannover.de",
        "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
        "doi": "10.25835/0078042",
        "doi_date_published": "2020-06-29",
        "doi_publisher": "LUIS",
        "doi_status": "True",
        "domain": "https://data.uni-hannover.de",
        "have_copyright": "Yes",
        "id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
        "isopen": False,
        "license_id": "CC-BY-3.0",
        "license_title": "CC-BY-3.0",
        "maintainer": "Clemens Huebler",
        "maintainer_email": "c.huebler@isd.uni-hannover.de",
        "metadata_created": "2021-10-07T09:58:55.243407",
        "metadata_modified": "2021-10-07T09:58:55.243416",
        "name": "luh-windturbine-simulation-for-meta-modelling",
        "notes": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).\r\nFor further information, it is referred to \"Huebler, C., & Rolfes, R. (2020). Analysis of the influence of climate change on the fatigue lifetime of offshore wind turbines using imprecise probabilities. Wind Energy. 2020;1–15.\"",
        "num_resources": 2,
        "num_tags": 3,
        "organization": {
            "id": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
            "name": "institut-fur-statik-und-dynamik",
            "title": "Institut für Statik und Dynamik",
            "type": "organization",
            "description": "(Institute of Structural Analysis) \r\nAppelstraße 9A \r\n__30167 Hannover (Germany)__\r\n\r\nhttps://www.isd.uni-hannover.de/en/institute/",
            "image_url": "",
            "created": "2021-10-07T11:46:15.762388",
            "is_organization": True,
            "approval_status": "approved",
            "state": "active"
        },
        "owner_org": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
        "private": False,
        "repository_name": "Leibniz University Hannover",
        "services_used_list": "",
        "source_metadata_created": "2020-06-29T13:56:20.726566",
        "source_metadata_modified": "2021-07-06T09:21:41.322946",
        "state": "active",
        "terms_of_usage": "Yes",
        "title": "Wind Turbine Simulation Data for Meta-Modelling",
        "type": "vdataset",
        "url": "https://data.uni-hannover.de/dataset/windturbine-simulation-for-meta-modelling",
        "version": "",
        "resources": [
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:56:24.253776",
                "datastore_active": False,
                "description": "",
                "downloadall_datapackage_hash": "98b5bd1da7a98e0a79ab9dae7e68f8cd",
                "downloadall_metadata_modified": "2021-07-06T09:21:25.079814",
                "format": "ZIP",
                "hash": "",
                "id": "da3a4b40-c6b3-42de-87a4-4ea60c441910",
                "last_modified": "2021-07-06T09:21:36.339262",
                "metadata_modified": "2021-10-07T09:58:55.231269",
                "mimetype": "application/zip",
                "mimetype_inner": None,
                "name": "All resource data",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 0,
                "resource_type": None,
                "revision_id": "5b858701-baff-4dff-86a8-06cb0c01f224",
                "size": 875,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/da3a4b40-c6b3-42de-87a4-4ea60c441910/download/windturbine-simulation-for-meta-modelling-otpq81.zip",
                "url_type": ""
            },
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:59:45.579275",
                "datastore_active": False,
                "description": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).",
                "format": "TXT",
                "hash": "",
                "id": "0f24dea1-53b3-4cb9-afa4-16b342524aa8",
                "last_modified": "2020-06-29T13:59:45.533215",
                "metadata_modified": "2021-10-07T09:58:55.233372",
                "mimetype": "text/plain",
                "mimetype_inner": None,
                "name": "Metamodeldata.txt",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 1,
                "resource_type": None,
                "revision_id": "f5dad358-82bc-44cd-84a8-5f68f14a774e",
                "size": 1142901,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/0f24dea1-53b3-4cb9-afa4-16b342524aa8/download/metamodeldata.txt",
                "url_type": ""
            }
        ],
        "tags": [
            {
                "display_name": "FAST",
                "id": "235ed4d9-3def-4174-bb4d-51950abe8813",
                "name": "FAST",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "meta-model",
                "id": "2c83feeb-a00e-4821-91b1-c42fb828a3ad",
                "name": "meta-model",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "wind energy",
                "id": "81223f1d-955d-4ff4-8be0-1fda56b540ba",
                "name": "wind energy",
                "state": "active",
                "vocabulary_id": None
            }
        ],
        "groups": [],
        "relationships_as_subject": [],
        "relationships_as_object": []
    }

resumption_token_ok = {'resumptionToken': 'rows=100@@searchMark=10.22000/72@@from=0001-01-01T00:00:00Z@@total=179@@until=9999-12-31T23:59:59Z@@metadataPrefix=radar', 'completeListSize': '179'}

resumption_token_empty = {'resumptionToken': ''}

expected_list_of_dict_from_osnadata = [{'header': {'identifier': 'doi:10.26249/FK2/48FTWW', 'datestamp': '2024-07-12T00:00:00Z'}, 'metadata': {'osnaDataDataset': {'identifier': '10.26249/FK2/48FTWW', 'identifierType': 'DOI', 'creators': [{'creator': {'creatorName': {'creatorName': 'Margheritis, Eleonora Germana', 'nameType': 'Personal'}, 'givenName': 'Eleonora Germana', 'familyName': 'Margheritis', 'nameIdentifier': {'nameIdentifier': '0000-0003-0571-3563', 'nameIdentifierScheme': 'ORCID'}}}, {'creator': {'creatorName': {'creatorName': 'Cosentino, Katia', 'nameType': 'Personal'}, 'givenName': 'Katia', 'familyName': 'Cosentino', 'nameIdentifier': {'nameIdentifier': '0000-0002-3796-3500', 'nameIdentifierScheme': 'ORCID'}}}], 'titles': [{'title': {'title': 'Cooperativity of cysteines governs GSDMD palmitoylation-mediated membrane targeting and assembly'}}], 'publisher': 'osnaData', 'publicationYear': '2024', 'subjectAreas': [{'subject': {'subject': 'Medicine, Health and Life Sciences'}}], 'resourceType': {'resourceType': None, 'resourceTypeGeneral': 'Dataset'}, 'rightsList': [{'rights': {'rights': {'rights': None, 'rightsURI': 'info:eu-repo/semantics/openAccess'}}}], 'descriptions': [{'description': {'description': 'Gasdermin D (GSDMD) executes cell death program pyroptosis by assembling into oligomers that permeabilize the plasma membrane. Here, by single-molecule imaging, we elucidate the yet elusive mechanism of GSDMD pore assembly and the role of cysteines in GSDMD oligomerization. We show that GSDMD preassembles at the membrane into dimeric and trimeric building blocks that can either insert the membrane or further assemble into higher-order oligomers, prior to membrane insertion. Cys39, Cys57, and Cys192 are the only relevant cysteines in GSDMD oligomerization. S-palmitoylation of Cys192 controls GSDMD membrane targeting together with negatively charged lipids. Importantly, simultaneous Cys39/57/192-to-Ala mutations, but not Cys192 or the Cys39/57 pair individually, completely abolish GSDMD insertion into artificial membranes and the plasma membrane in cells. Finally, either Cys192 or the Cys39/Cys57 pair are sufficient to form dimers/trimers, but they are all required for functional higher-order oligomer formation. Overall, our study unveils a cooperative role of Cys192 palmitoylation-mediated membrane binding and Cys39/57/192-mediated oligomerization in GSDMD pore assembly. This study supports a model where GSDMD oligomerization relies on a two-step mechanism mediated by cysteines.\nRaw and Source data can be accessed via the link.'}, 'descriptionType': 'Abstract'}], 'keywords': [], 'contributors': [{'contributor': {'contributorName': {'contributorName': 'Margheritis, Eleonora Germana', 'nameType': 'Personal'}, 'givenName': 'Eleonora Germana', 'familyName': 'Margheritis', 'affiliation': 'Department of Biology/Chemistry and Center for Cellular Nanoanalytics (CellNanOs), University of Osnabrück, Germany'}}, {'contributor': {'contributorName': {'contributorName': 'Cosentino, Katia', 'nameType': 'Personal'}, 'givenName': 'Katia', 'familyName': 'Cosentino', 'affiliation': 'Department of Biology/Chemistry and Center for Cellular Nanoanalytics (CellNanOs), University of Osnabrück, Germany'}}], 'language': {}, 'alternateIdentifiers': [], 'relatedIdentifiers': [{'relatedIdentifier': {'relatedIdentifier': '10.17632/zdh4d5ws2z.2'}, 'relationType': 'IsCitedBy', 'relatedIdentifierType': 'DOI'}, {'relatedIdentifier': {'relatedIdentifier': '10.1016/j.neunet.2020.11.004'}, 'relationType': 'IsCitedBy', 'relatedIdentifierType': 'DOI'}]}}}, {'header': {'identifier': 'doi:10.26249/FK2/4B3NSO', 'datestamp': '2022-05-03T01:00:00Z'}, 'metadata': {'osnaDataDataset': {'identifier': '10.26249/FK2/4B3NSO', 'identifierType': 'DOI', 'creators': [{'creator': {'creatorName': {'creatorName': 'Niehoff, Steffen', 'nameType': 'Personal'}, 'givenName': 'Steffen', 'familyName': 'Niehoff'}}, {'creator': {'creatorName': {'creatorName': 'Holst, Hajo', 'nameType': 'Personal'}, 'givenName': 'Hajo', 'familyName': 'Holst'}}, {'creator': {'creatorName': {'creatorName': 'Fessler, Agnes', 'nameType': 'Personal'}, 'givenName': 'Agnes', 'familyName': 'Fessler'}}], 'titles': [{'title': {'title': 'Replikationsdaten für Artikel "Covid-19, Ungleichheit und (Erwerbs)-Arbeit – zur Relevanz sozialer Klasse in der Pandemie"'}}], 'publisher': 'osnaData', 'publicationYear': '2022', 'subjectAreas': [{'subject': {'subject': 'Social Sciences'}}], 'resourceType': {'resourceType': None, 'resourceTypeGeneral': 'Dataset'}, 'rightsList': [{'rights': {'rights': {'rights': None, 'rightsURI': 'info:eu-repo/semantics/openAccess'}}}], 'descriptions': [{'description': {'description': 'Der Erwerbstätigensurvey (Arbeitswelt-Monitor) untersucht in der Frühphase der COVID-19-Pandemie die Auswirkungen der Pandemie und der Eindämmungsmaßnahmen auf die Arbeitswelt in fünf Feldern: Infektionsrisiken am Arbeitsplatz, wirtschaftliche Lasten, mobiles Arbeiten, Arbeitsbedingungen und Vereinbarkeit von Erwerbsarbeit und Kinderbetreuung. Dazu werden für unterschiedliche Betroffenheiten in diesen Themenfeldern logistische Regressionen berechnet, um besondere Ungleichheiten in der Sozialstruktur zu verorten.\n\nDie hier eingestellten Daten und das dazugehörige do-File dienen der Replikation der dazu publizierten Ergebnise.'}, 'descriptionType': 'Abstract'}], 'keywords': [], 'contributors': [{'contributor': {'contributorName': {'contributorName': 'Niehoff, Steffen', 'nameType': 'Personal'}, 'givenName': 'Steffen', 'familyName': 'Niehoff', 'affiliation': 'Universität Osnabrück'}}], 'language': {}, 'alternateIdentifiers': [], 'relatedIdentifiers': []}}}, {'header': {'identifier': 'doi:10.26249/FK2/5AXRBJ', 'datestamp': '2024-02-01T01:00:00Z'}, 'metadata': {'osnaDataDataset': {'identifier': '10.26249/FK2/5AXRBJ', 'identifierType': 'DOI', 'creators': [{'creator': {'creatorName': {'creatorName': 'Lange, Silke', 'nameType': 'Personal'}, 'givenName': 'Silke', 'familyName': 'Lange'}}], 'titles': [{'title': {'title': 'SUF LBS-Monitor: 4. Erhebungswelle'}}], 'publisher': 'osnaData', 'publicationYear': '2024', 'subjectAreas': [{'subject': {'subject': 'Social Sciences'}}, {'subject': {'subject': 'Lehrerbildung'}}, {'subject': {'subject': 'Lehramtsstudium'}}, {'subject': {'subject': 'berufliche Lehrerbildung'}}], 'resourceType': {'resourceType': None, 'resourceTypeGeneral': 'Dataset'}, 'rightsList': [{'rights': {'rights': {'rights': None, 'rightsURI': 'info:eu-repo/semantics/openAccess'}}}], 'descriptions': [{'description': {'description': 'Die Daten stammen aus einer Längsschnittstudie zur professionsbezogenen Entwicklung von Studierenden in Studiengängen für das Lehramt an berufsbildenden Schulen (LBS-Monitor). Die Studie wird durchgeführt im Rahmen des Projektes "DEIN LBS-Campus", das vom Bundesministerium für Bildung und Forschung gefördert wird (Laufzeit: 01.03.2020-31.12.2023). Über Onlinebefragungen an mehreren Standorten der hochschulischen beruflichen Lehrerbildung werden soziodemographische Merkmale der Studierenden, Angaben zum Studium und zu den Studienvoraussetzungen, Merkmale der professionsbezogenen Entwicklung, verschiedene Studien- und berufsbezogene Aspekte und ausgewählte Qualitätsaspekte sowie formale Leistungsindikatoren erfasst. Die 4. Welle wurde im Wintersemester 2022/23 durchgeführt. Zur Verfügung gestellt werden eine Scientific-Use-File (SUF) des Wellendatensatzes und des Gesamtdatensatzes. Beide stehen im SPSS-Format zur Verfügung. Die bereinigte SUF des Wellendatensatzes umfasst 223 Fälle und 382 Variablen. Die SUF Gesamtdatensatzes umfasst 1.191 Fälle und 1.168 Variablen. Die Daten werden über verschiedene Berichte dokumentiert. Das Skalenhandbuch enthält eine Dokumentation des Gesamtdatensatzes und wird über die Erhebungswellen fortgeschrieben. Das Codebook, der Datenbericht und der Wellenbericht beziehen sich auf die 4. Erhebungswelle. Das Codebook dokumentiert die erhobenen Variablen hinsichtlich Fragestellung und Codierung, im Datenbericht werden statistische Kennwerte berichtet. Die Erhebung und ausgewählte Analyseergebnisse sind im Wellenbericht zu finden.'}, 'descriptionType': 'Abstract'}], 'keywords': [], 'contributors': [{'contributor': {'contributorName': {'contributorName': 'Lange, Silke', 'nameType': 'Personal'}, 'givenName': 'Silke', 'familyName': 'Lange'}}], 'language': {}, 'alternateIdentifiers': [], 'relatedIdentifiers': []}}}]
osnadata_all_datasets_list_response = [{'repository_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'vdataset', 'source_metadata_created': '2024', 'source_metadata_modified': '', 'owner_org': 'osnadata', 'author': 'Margheritis, Eleonora Germana', 'author_email': '', 'doi': '10.26249/FK2/48FTWW', 'doi_date_published': '2024', 'doi_publisher': '', 'doi_status': 'True', 'license_id': '', 'license_title': None, 'name': 'osn-doi-10-26249-fk2-48ftww', 'notes': 'Abstract: Gasdermin D (GSDMD) executes cell death program pyroptosis by assembling into oligomers that permeabilize the plasma membrane. Here, by single-molecule imaging, we elucidate the yet elusive mechanism of GSDMD pore assembly and the role of cysteines in GSDMD oligomerization. We show that GSDMD preassembles at the membrane into dimeric and trimeric building blocks that can either insert the membrane or further assemble into higher-order oligomers, prior to membrane insertion. Cys39, Cys57, and Cys192 are the only relevant cysteines in GSDMD oligomerization. S-palmitoylation of Cys192 controls GSDMD membrane targeting together with negatively charged lipids. Importantly, simultaneous Cys39/57/192-to-Ala mutations, but not Cys192 or the Cys39/57 pair individually, completely abolish GSDMD insertion into artificial membranes and the plasma membrane in cells. Finally, either Cys192 or the Cys39/Cys57 pair are sufficient to form dimers/trimers, but they are all required for functional higher-order oligomer formation. Overall, our study unveils a cooperative role of Cys192 palmitoylation-mediated membrane binding and Cys39/57/192-mediated oligomerization in GSDMD pore assembly. This study supports a model where GSDMD oligomerization relies on a two-step mechanism mediated by cysteines.\nRaw and Source data can be accessed via the link.', 'organization': {'approval_status': 'approved', 'description': 'The Research Data Repository of the Osnabrück University.', 'display_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'image_display_url': 'logo-osnaData.png', 'image_url': 'logo-osnaData.png', 'is_organization': True, 'name': 'osnadata', 'state': 'active', 'title': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'organization'}, 'title': 'Cooperativity of cysteines governs gsdmd palmitoylation-mediated membrane targeting and assembly', 'url': 'https://doi.org/10.26249/FK2/48FTWW', 'citation': [], 'givenName': 'Eleonora Germana', 'familyName': 'Margheritis', 'orcid': '0000-0003-0571-3563', 'extra_authors': [{'extra_author': 'Cosentino, Katia', 'givenName': 'Katia', 'familyName': 'Cosentino', 'orcid': '0000-0002-3796-3500'}], 'publication_year': '2024', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Medicine, Health and Life Sciences'}], 'resource_type': 'Dataset', 'related_identifiers': [{'identifier': '10.17632/zdh4d5ws2z.2', 'identifier_type': 'DOI', 'relation_type': 'IsCitedBy'}, {'identifier': '10.1016/j.neunet.2020.11.004', 'identifier_type': 'DOI', 'relation_type': 'IsCitedBy'}]}, {'repository_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'vdataset', 'source_metadata_created': '2022', 'source_metadata_modified': '', 'owner_org': 'osnadata', 'author': 'Niehoff, Steffen', 'author_email': '', 'doi': '10.26249/FK2/4B3NSO', 'doi_date_published': '2022', 'doi_publisher': '', 'doi_status': 'True', 'license_id': '', 'license_title': None, 'name': 'osn-doi-10-26249-fk2-4b3nso', 'notes': 'Abstract: Der Erwerbstätigensurvey (Arbeitswelt-Monitor) untersucht in der Frühphase der COVID-19-Pandemie die Auswirkungen der Pandemie und der Eindämmungsmaßnahmen auf die Arbeitswelt in fünf Feldern: Infektionsrisiken am Arbeitsplatz, wirtschaftliche Lasten, mobiles Arbeiten, Arbeitsbedingungen und Vereinbarkeit von Erwerbsarbeit und Kinderbetreuung. Dazu werden für unterschiedliche Betroffenheiten in diesen Themenfeldern logistische Regressionen berechnet, um besondere Ungleichheiten in der Sozialstruktur zu verorten.\n\nDie hier eingestellten Daten und das dazugehörige do-File dienen der Replikation der dazu publizierten Ergebnise.', 'organization': {'approval_status': 'approved', 'description': 'The Research Data Repository of the Osnabrück University.', 'display_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'image_display_url': 'logo-osnaData.png', 'image_url': 'logo-osnaData.png', 'is_organization': True, 'name': 'osnadata', 'state': 'active', 'title': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'organization'}, 'title': 'Replikationsdaten für artikel "covid-19, ungleichheit und (erwerbs)-arbeit – zur relevanz sozialer klasse in der pandemie"', 'url': 'https://doi.org/10.26249/FK2/4B3NSO', 'citation': [], 'givenName': 'Steffen', 'familyName': 'Niehoff', 'orcid': '', 'extra_authors': [{'extra_author': 'Holst, Hajo', 'givenName': 'Hajo', 'familyName': 'Holst', 'orcid': ''}, {'extra_author': 'Fessler, Agnes', 'givenName': 'Agnes', 'familyName': 'Fessler', 'orcid': ''}], 'publication_year': '2022', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Social Sciences'}], 'resource_type': 'Dataset'}, {'repository_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'vdataset', 'source_metadata_created': '2024', 'source_metadata_modified': '', 'owner_org': 'osnadata', 'author': 'Lange, Silke', 'author_email': '', 'doi': '10.26249/FK2/5AXRBJ', 'doi_date_published': '2024', 'doi_publisher': '', 'doi_status': 'True', 'license_id': '', 'license_title': None, 'name': 'osn-doi-10-26249-fk2-5axrbj', 'notes': 'Abstract: Die Daten stammen aus einer Längsschnittstudie zur professionsbezogenen Entwicklung von Studierenden in Studiengängen für das Lehramt an berufsbildenden Schulen (LBS-Monitor). Die Studie wird durchgeführt im Rahmen des Projektes "DEIN LBS-Campus", das vom Bundesministerium für Bildung und Forschung gefördert wird (Laufzeit: 01.03.2020-31.12.2023). Über Onlinebefragungen an mehreren Standorten der hochschulischen beruflichen Lehrerbildung werden soziodemographische Merkmale der Studierenden, Angaben zum Studium und zu den Studienvoraussetzungen, Merkmale der professionsbezogenen Entwicklung, verschiedene Studien- und berufsbezogene Aspekte und ausgewählte Qualitätsaspekte sowie formale Leistungsindikatoren erfasst. Die 4. Welle wurde im Wintersemester 2022/23 durchgeführt. Zur Verfügung gestellt werden eine Scientific-Use-File (SUF) des Wellendatensatzes und des Gesamtdatensatzes. Beide stehen im SPSS-Format zur Verfügung. Die bereinigte SUF des Wellendatensatzes umfasst 223 Fälle und 382 Variablen. Die SUF Gesamtdatensatzes umfasst 1.191 Fälle und 1.168 Variablen. Die Daten werden über verschiedene Berichte dokumentiert. Das Skalenhandbuch enthält eine Dokumentation des Gesamtdatensatzes und wird über die Erhebungswellen fortgeschrieben. Das Codebook, der Datenbericht und der Wellenbericht beziehen sich auf die 4. Erhebungswelle. Das Codebook dokumentiert die erhobenen Variablen hinsichtlich Fragestellung und Codierung, im Datenbericht werden statistische Kennwerte berichtet. Die Erhebung und ausgewählte Analyseergebnisse sind im Wellenbericht zu finden.', 'organization': {'approval_status': 'approved', 'description': 'The Research Data Repository of the Osnabrück University.', 'display_name': 'osnaData (The Research Data Repository of the Osnabrück University)', 'image_display_url': 'logo-osnaData.png', 'image_url': 'logo-osnaData.png', 'is_organization': True, 'name': 'osnadata', 'state': 'active', 'title': 'osnaData (The Research Data Repository of the Osnabrück University)', 'type': 'organization'}, 'title': 'Suf lbs-monitor: 4. erhebungswelle', 'url': 'https://doi.org/10.26249/FK2/5AXRBJ', 'citation': [], 'givenName': 'Silke', 'familyName': 'Lange', 'orcid': '', 'publication_year': '2024', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Social Sciences'}, {'subject_area_additional': '', 'subject_area_name': 'Lehrerbildung'}, {'subject_area_additional': '', 'subject_area_name': 'Lehramtsstudium'}, {'subject_area_additional': '', 'subject_area_name': 'berufliche Lehrerbildung'}], 'resource_type': 'Dataset'}]

ckan_dict_of_imported_dataset = dataset = {
    "author": "Margheritis, Eleonora Germana",
    "author_email": "",
    "citation": [],
    "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
    "doi": "10.26249/FK2/48FTWW",
    "doi_date_published": "2024",
    "doi_publisher": "",
    "doi_status": "True",
    "familyName": "Margheritis",
    "givenName": "Eleonora Germana",
    "id": "b26e7805-53cc-47b1-a829-eb1b5ca18fbc",
    "isopen": False,
    "license_id": "",
    "license_title": "",
    "metadata_created": "2025-03-05T07:51:10.983641",
    "metadata_modified": "2025-03-05T07:51:10.983656",
    "name": "osn-doi-10-26249-fk2-48ftww",
    "notes": "Abstract: Gasdermin D (GSDMD) executes cell death program pyroptosis by assembling into oligomers that permeabilize the plasma membrane. Here, by single-molecule imaging, we elucidate the yet elusive mechanism of GSDMD pore assembly and the role of cysteines in GSDMD oligomerization. We show that GSDMD preassembles at the membrane into dimeric and trimeric building blocks that can either insert the membrane or further assemble into higher-order oligomers, prior to membrane insertion. Cys39, Cys57, and Cys192 are the only relevant cysteines in GSDMD oligomerization. S-palmitoylation of Cys192 controls GSDMD membrane targeting together with negatively charged lipids. Importantly, simultaneous Cys39/57/192-to-Ala mutations, but not Cys192 or the Cys39/57 pair individually, completely abolish GSDMD insertion into artificial membranes and the plasma membrane in cells. Finally, either Cys192 or the Cys39/Cys57 pair are sufficient to form dimers/trimers, but they are all required for functional higher-order oligomer formation. Overall, our study unveils a cooperative role of Cys192 palmitoylation-mediated membrane binding and Cys39/57/192-mediated oligomerization in GSDMD pore assembly. This study supports a model where GSDMD oligomerization relies on a two-step mechanism mediated by cysteines.\nRaw and Source data can be accessed via the link.",
    "num_resources": 0,
    "num_tags": 0,
    "orcid": "0000-0003-0571-3563",
    "organization": {
        "id": "28d5ebd1-6c25-4814-a001-50f8ae0c9f29",
        "name": "osnadata",
        "title": "osnaData (The Research Data Repository of the Osnabrück University)",
        "type": "organization",
        "description": "The Research Data Repository of the Osnabrück University.",
        "image_url": "logo-osnaData.png",
        "created": "2025-03-05T08:51:10.808700",
        "is_organization": True,
        "approval_status": "approved",
        "state": "active"
    },
    "owner_org": "28d5ebd1-6c25-4814-a001-50f8ae0c9f29",
    "private": False,
    "publication_year": "2024",
    "repository_name": "osnaData (The Research Data Repository of the Osnabrück University)",
    "resource_type": "Dataset",
    "services_used_list": "",
    "source_metadata_created": "2024",
    "source_metadata_modified": "",
    "state": "active",
    "tag_string": "",
    "title": "Cooperativity of cysteines governs gsdmd palmitoylation-mediated membrane targeting and assembly",
    "type": "vdataset",
    "url": "https://doi.org/10.26249/FK2/48FTWW",
    "extra_authors": [
        {
            "extra_author": "Cosentino, Katia",
            "familyName": "Cosentino",
            "givenName": "Katia",
            "orcid": "0000-0002-3796-3500"
        }
    ],
    "subject_areas": [
        {
            "subject_area_additional": "",
            "subject_area_name": "Medicine, Health and Life Sciences"
        }
    ],
    "resources": [],
    "tags": [],
    "groups": [],
    "relationships_as_subject": [],
    "relationships_as_object": []
}

osnadata_dict_of_imported_dataset = osnadata_all_datasets_list_response[0]