# LOCAL CKAN DATA
# ***************
local_organization_data = {'approval_status': 'approved',
                                'created': '2021-07-22T14:33:24.825599',
                                'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                'display_name': 'TIB',
                                'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                'image_display_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'is_organization': True,
                                'name': 'tib-iasis',
                                'num_followers': 0,
                                'state': 'active',
                                'title': 'TIB',
                                'type': 'organization',
                                'tags': []}


local_dataset_data = {'author': 'Autodesk',
                      'author_email': '',
                      'creator_user_id': '6114fb41-d314-4c35-b8c1-278c9f997579',
                      'id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                      'isopen': True,
                      'license_id': 'cc-by',
                      'license_title': 'Creative Commons Attribution',
                      'license_url': 'http://www.opendefinition.org/licenses/cc-by',
                      'maintainer': '',
                      'maintainer_email': '',
                      'metadata_created': '2021-07-26T06:19:07.491127',
                      'metadata_modified': '2021-07-26T06:19:07.491139',
                      'name': 'example-cad',
                      'notes': 'Example usage of CAD visualization in 2D and 3D using CKAN Views.',
                      'num_resources': 2,
                      'num_tags': 0,
                      'organization': {'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                       'name': 'tib-iasis',
                                       'title': 'TIB',
                                       'type': 'organization',
                                       'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                       'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                       'created': '2021-07-22T14:33:24.825599',
                                       'is_organization': True,
                                       'approval_status': 'approved',
                                       'state': 'active'},
                      'owner_org': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                      'private': False,
                      'state': 'active',
                      'title': 'Example CAD',
                      'type': 'dataset',
                      'url': 'https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html',
                      'version': '',
                      'extras': [{'key': 'foobar', 'value': 'baz'}],
                      'resources': [{'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:37:19.897441',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '4ee0ec1c-c72b-4bad-be73-364a735cea5c',
                                     'last_modified': '2017-12-01T16:52:30.511835',
                                     'metadata_modified': '2021-07-26T05:23:45.398718',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 2D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 0,
                                     'resource_type': None,
                                     'size': 169807,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/Drive_shaft.dwg',
                                     'url_type': ''},
                                    {'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:40:23.217872',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '1342ec64-f18e-4860-93cc-f6dd194d56ec',
                                     'last_modified': '2017-12-01T16:53:23.693615',
                                     'metadata_modified': '2021-07-26T05:23:45.401967',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 3D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 1,
                                     'resource_type': None,
                                     'size': 733036,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/visualization_-_aerial.dwg',
                                     'url_type': ''}],
                      'tags': [],
                      'groups': [],
                      'relationships_as_subject': [],
                      'relationships_as_object': []}

# PANGEA API DATA
# ***************


pangea_dataset_parsed_to_dict = {'header': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786524',
                                           'datestamp': '2022-11-11T13:48:06Z'},
                                'metadata': {'pangeaDataset': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786524',
                                                               'authors': [{'author': {'lastName': 'Colacevich',
                                                                                       'firstName': 'Andrea',
                                                                                       'eMail': 'colacevich2@unisi.it'}},
                                                                           {'author': {'lastName': 'Caruso',
                                                                                       'firstName': 'Tancredi',
                                                                                       'orcid': '0000-0002-3607-9609'}},
                                                                           {'author': {'lastName': 'Borghini',
                                                                                       'firstName': 'Francesca',
                                                                                       'eMail': 'borghini@unisi.it'}},
                                                                           {'author': {'lastName': 'Bargagli',
                                                                                       'firstName': 'Roberto'}}],
                                                               'title': 'Floral and faunal characteristics and content of photosynthetic pigment in soils of northern Victoria Land, Antarctica',
                                                               'year': '2009',
                                                               'technicalInfo': {'xmlLastModified': '2022-11-11T13:48:06Z',
                                                                                 'lastModified': '2017-08-08T07:09:25',
                                                                                 'filename': 'Colacevich_2009',
                                                                                 'mimeType': 'application/zip',
                                                                                 'status': 'published',
                                                                                 'status_num': '4',
                                                                                 'DOIRegistryStatus': 'registered',
                                                                                 'DOIRegistryStatus_num': '4',
                                                                                 'DOIRegistrationDate': '2012-08-22T03:10:49',
                                                                                 'hierarchyLevel': 'parent',
                                                                                 'collectionType': 'publication series',
                                                                                 'collectionType_num': '4',
                                                                                 'collectionChilds': 'D786522,D786523',
                                                                                 'loginOption': 'unrestricted',
                                                                                 'loginOption_num': '1'},
                                                               'setSpecs': ['citable', 'supplement',
                                                                            'topicAgriculture',
                                                                            'topicLithosphere'],
                                                               'license': [{'license': {'label': 'CC-BY-3.0',
                                                                                        'name': 'Creative Commons Attribution 3.0 Unported',
                                                                                        'URI': 'https://creativecommons.org/licenses/by/3.0/'}}],
                                                               'abstract': 'Although soil algae are among the main primary producers in most terrestrial ecosystems of continental Antarctica, there are very few quantitative studies on their relative proportion in the main algal groups and on how their distribution is affected by biotic and abiotic factors. Such knowledge is essential for understanding the functioning of Antarctic terrestrial ecosystems. We therefore analyzed biological soil crusts from northern Victoria Land to determine their pH, electrical conductivity (EC), water content (W), total and organic C (TC and TOC) and total N (TN) contents, and the presence and abundance of photosynthetic pigments. In particular, the latter were tested as proxies for biomass and coarse-resolution community structure. Soil samples were collected from five sites with known soil algal communities and the distribution of pigments was shown to reflect differences in the relative proportions of Chlorophyta, Cyanophyta and Bacillariophyta in these sites. Multivariate and univariate models strongly indicated that almost all soil variables (EC, W, TOC and TN) were important environmental correlates of pigment distribution. However, a significant amount of variation is independent of these soil variables and may be ascribed to local variability such as changes in microclimate at varying spatial and temporal scales. There are at least five possible sources of local variation: pigment preservation, temporal variations in water availability, temporal and spatial interactions among environmental and biological components, the local-scale patchiness of organism distribution, and biotic interactions.\n',
                                                               'keywords': ['ipy', 'Agriculture', 'crop yield', 'maize', 'rice', 'soybean', 'wheat']}}}

pangea_dataset_parsed_to_ckan_dict = {'repository_name': 'PANGEA (Data Publisher for Earth & Environmental Science)',
                                      'type': 'vdataset',
                                      'source_metadata_created': '2009',
                                      'source_metadata_modified': '',
                                      'owner_org': 'pangea',
                                      'author': 'Colacevich Andrea',
                                      'author_email': '',
                                      'doi': '10.1594/PANGAEA.786524',
                                      'doi_date_published': '2009',
                                      'doi_publisher': '',
                                      'doi_status': 'True',
                                      'license_id': 'CC-BY-3.0',
                                      'license_title': 'Creative Commons Attribution 3.0 Unported',
                                      'name': 'png-doi-10-1594-pangaea-786524',
                                      'notes': 'Although soil algae are among the main primary producers in most terrestrial ecosystems of continental Antarctica, there are very few quantitative studies on their relative proportion in the main algal groups and on how their distribution is affected by biotic and abiotic factors. Such knowledge is essential for understanding the functioning of Antarctic terrestrial ecosystems. We therefore analyzed biological soil crusts from northern Victoria Land to determine their pH, electrical conductivity (EC), water content (W), total and organic C (TC and TOC) and total N (TN) contents, and the presence and abundance of photosynthetic pigments. In particular, the latter were tested as proxies for biomass and coarse-resolution community structure. Soil samples were collected from five sites with known soil algal communities and the distribution of pigments was shown to reflect differences in the relative proportions of Chlorophyta, Cyanophyta and Bacillariophyta in these sites. Multivariate and univariate models strongly indicated that almost all soil variables (EC, W, TOC and TN) were important environmental correlates of pigment distribution. However, a significant amount of variation is independent of these soil variables and may be ascribed to local variability such as changes in microclimate at varying spatial and temporal scales. There are at least five possible sources of local variation: pigment preservation, temporal variations in water availability, temporal and spatial interactions among environmental and biological components, the local-scale patchiness of organism distribution, and biotic interactions.\n',
                                      'organization': {'approval_status': 'approved',
                                                       'description': 'PANGEA (Data Publisher for Earth & Environmental Science): The information system PANGAEA is operated as an Open Access library aimed at archiving, publishing and distributing georeferenced data from earth system research. PANGAEA guarantees long-term availability (greater than 10 years) of its content. PANGAEA is open to any project, institution, or individual scientist to use or to archive and publish data. PANGAEA focuses on georeferenced observational data, experimental data, and models/simulations. Citability, comprehensive metadata descriptions, interoperability of data and metadata, a high degree of structural and semantic harmonization of the data inventory as well as the commitment of the hosting institutions ensures FAIRness of archived data.',
                                                       'display_name': 'PANGEA',
                                                       'image_display_url': '/images/pangea-logo.png',
                                                       'image_url': '/images/pangea-logo.png',
                                                       'is_organization': True,
                                                       'name': 'pangea',
                                                       'state': 'active',
                                                       'title': 'PANGEA (Agriculture)',
                                                       'type': 'organization'},
                                      'title': 'Floral and faunal characteristics and content of photosynthetic pigment in soils of northern Victoria Land, Antarctica',
                                      'url': 'https://doi.org/10.1594/PANGAEA.786524',
                                      'orcid': '',
                                      'extra_authors': [{'extra_author': 'Caruso Tancredi',
                                                         'orcid': '0000-0002-3607-9609'},
                                                        {'extra_author': 'Borghini Francesca',
                                                         'orcid': ''},
                                                        {'extra_author': 'Bargagli Roberto',
                                                         'orcid': ''}],
                                      'tags': [{'display_name': 'ipy',
                                                'name': 'ipy',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'Agriculture',
                                                'name': 'Agriculture',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'crop yield',
                                                'name': 'crop yield',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'maize',
                                                'name': 'maize',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'rice',
                                                'name': 'rice',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'soybean',
                                                'name': 'soybean',
                                                'state': 'active',
                                                'vocabulary_id': None},
                                               {'display_name': 'wheat',
                                                'name': 'wheat',
                                                'state': 'active',
                                                'vocabulary_id': None}],
                                      'publication_year': '2009',
                                      'subject_areas': [{'subject_area_additional': '',
                                                         'subject_area_name': 'Agriculture'},
                                                        {'subject_area_additional': '',
                                                         'subject_area_name': 'Lithosphere'}],
                                      'resource_type': 'application/zip - filename: Colacevich_2009'}



LDM_imported_dataset = {
        "author": "Clemens Huebler",
        "author_email": "c.huebler@isd.uni-hannover.de",
        "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
        "doi": "10.25835/0078042",
        "doi_date_published": "2020-06-29",
        "doi_publisher": "LUIS",
        "doi_status": "True",
        "domain": "https://data.uni-hannover.de",
        "have_copyright": "Yes",
        "id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
        "isopen": False,
        "license_id": "CC-BY-3.0",
        "license_title": "CC-BY-3.0",
        "maintainer": "Clemens Huebler",
        "maintainer_email": "c.huebler@isd.uni-hannover.de",
        "metadata_created": "2021-10-07T09:58:55.243407",
        "metadata_modified": "2021-10-07T09:58:55.243416",
        "name": "luh-windturbine-simulation-for-meta-modelling",
        "notes": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).\r\nFor further information, it is referred to \"Huebler, C., & Rolfes, R. (2020). Analysis of the influence of climate change on the fatigue lifetime of offshore wind turbines using imprecise probabilities. Wind Energy. 2020;1–15.\"",
        "num_resources": 2,
        "num_tags": 3,
        "organization": {
            "id": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
            "name": "institut-fur-statik-und-dynamik",
            "title": "Institut für Statik und Dynamik",
            "type": "organization",
            "description": "(Institute of Structural Analysis) \r\nAppelstraße 9A \r\n__30167 Hannover (Germany)__\r\n\r\nhttps://www.isd.uni-hannover.de/en/institute/",
            "image_url": "",
            "created": "2021-10-07T11:46:15.762388",
            "is_organization": True,
            "approval_status": "approved",
            "state": "active"
        },
        "owner_org": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
        "private": False,
        "repository_name": "Leibniz University Hannover",
        "services_used_list": "",
        "source_metadata_created": "2020-06-29T13:56:20.726566",
        "source_metadata_modified": "2021-07-06T09:21:41.322946",
        "state": "active",
        "terms_of_usage": "Yes",
        "title": "Wind Turbine Simulation Data for Meta-Modelling",
        "type": "vdataset",
        "url": "https://data.uni-hannover.de/dataset/windturbine-simulation-for-meta-modelling",
        "version": "",
        "resources": [
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:56:24.253776",
                "datastore_active": False,
                "description": "",
                "downloadall_datapackage_hash": "98b5bd1da7a98e0a79ab9dae7e68f8cd",
                "downloadall_metadata_modified": "2021-07-06T09:21:25.079814",
                "format": "ZIP",
                "hash": "",
                "id": "da3a4b40-c6b3-42de-87a4-4ea60c441910",
                "last_modified": "2021-07-06T09:21:36.339262",
                "metadata_modified": "2021-10-07T09:58:55.231269",
                "mimetype": "application/zip",
                "mimetype_inner": None,
                "name": "All resource data",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 0,
                "resource_type": None,
                "revision_id": "5b858701-baff-4dff-86a8-06cb0c01f224",
                "size": 875,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/da3a4b40-c6b3-42de-87a4-4ea60c441910/download/windturbine-simulation-for-meta-modelling-otpq81.zip",
                "url_type": ""
            },
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:59:45.579275",
                "datastore_active": False,
                "description": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).",
                "format": "TXT",
                "hash": "",
                "id": "0f24dea1-53b3-4cb9-afa4-16b342524aa8",
                "last_modified": "2020-06-29T13:59:45.533215",
                "metadata_modified": "2021-10-07T09:58:55.233372",
                "mimetype": "text/plain",
                "mimetype_inner": None,
                "name": "Metamodeldata.txt",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 1,
                "resource_type": None,
                "revision_id": "f5dad358-82bc-44cd-84a8-5f68f14a774e",
                "size": 1142901,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/0f24dea1-53b3-4cb9-afa4-16b342524aa8/download/metamodeldata.txt",
                "url_type": ""
            }
        ],
        "tags": [
            {
                "display_name": "FAST",
                "id": "235ed4d9-3def-4174-bb4d-51950abe8813",
                "name": "FAST",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "meta-model",
                "id": "2c83feeb-a00e-4821-91b1-c42fb828a3ad",
                "name": "meta-model",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "wind energy",
                "id": "81223f1d-955d-4ff4-8be0-1fda56b540ba",
                "name": "wind energy",
                "state": "active",
                "vocabulary_id": None
            }
        ],
        "groups": [],
        "relationships_as_subject": [],
        "relationships_as_object": []
    }

resumption_token_ok = {'resumptionToken': '7d35f2f1-768a-4ccd-9e85-9ec46f871800', 'expirationDate': '2022-11-22T08:08:22Z', 'cursor': '0'}

resumption_token_empty = {'resumptionToken': ''}

expected_list_of_dict_from_pangea = [{'header': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786524',
                                                 'datestamp': '2022-11-11T13:48:06Z'},
                                      'metadata': {'pangeaDataset': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786524',
                                                                     'authors': [{'author': {'lastName': 'Colacevich', 'firstName': 'Andrea', 'eMail': 'colacevich2@unisi.it'}},
                                                                                 {'author': {'lastName': 'Caruso', 'firstName': 'Tancredi', 'orcid': '0000-0002-3607-9609'}},
                                                                                 {'author': {'lastName': 'Borghini', 'firstName': 'Francesca', 'eMail': 'borghini@unisi.it'}},
                                                                                 {'author': {'lastName': 'Bargagli', 'firstName': 'Roberto'}}],
                                                                     'title': 'Floral and faunal characteristics and content of photosynthetic pigment in soils of northern Victoria Land, Antarctica',
                                                                     'year': '2009',
                                                                     'technicalInfo': {'xmlLastModified': '2022-11-11T13:48:06Z',
                                                                                       'lastModified': '2017-08-08T07:09:25',
                                                                                       'filename': 'Colacevich_2009',
                                                                                       'mimeType': 'application/zip',
                                                                                       'status': 'published',
                                                                                       'status_num': '4',
                                                                                       'DOIRegistryStatus': 'registered',
                                                                                       'DOIRegistryStatus_num': '4',
                                                                                       'DOIRegistrationDate': '2012-08-22T03:10:49',
                                                                                       'hierarchyLevel': 'parent',
                                                                                       'collectionType': 'publication series',
                                                                                       'collectionType_num': '4',
                                                                                       'collectionChilds': 'D786522,D786523',
                                                                                       'loginOption': 'unrestricted',
                                                                                       'loginOption_num': '1'},
                                                                     'setSpecs': ['citable', 'supplement', 'topicAgriculture', 'topicLithosphere'],
                                                                     'license': [{'license': {'label': 'CC-BY-3.0',
                                                                                              'name': 'Creative Commons Attribution 3.0 Unported',
                                                                                              'URI': 'https://creativecommons.org/licenses/by/3.0/'}}],
                                                                     'abstract': 'Although soil algae are among the main primary producers in most terrestrial ecosystems of continental Antarctica, there are very few quantitative studies on their relative proportion in the main algal groups and on how their distribution is affected by biotic and abiotic factors. Such knowledge is essential for understanding the functioning of Antarctic terrestrial ecosystems. We therefore analyzed biological soil crusts from northern Victoria Land to determine their pH, electrical conductivity (EC), water content (W), total and organic C (TC and TOC) and total N (TN) contents, and the presence and abundance of photosynthetic pigments. In particular, the latter were tested as proxies for biomass and coarse-resolution community structure. Soil samples were collected from five sites with known soil algal communities and the distribution of pigments was shown to reflect differences in the relative proportions of Chlorophyta, Cyanophyta and Bacillariophyta in these sites. Multivariate and univariate models strongly indicated that almost all soil variables (EC, W, TOC and TN) were important environmental correlates of pigment distribution. However, a significant amount of variation is independent of these soil variables and may be ascribed to local variability such as changes in microclimate at varying spatial and temporal scales. There are at least five possible sources of local variation: pigment preservation, temporal variations in water availability, temporal and spatial interactions among environmental and biological components, the local-scale patchiness of organism distribution, and biotic interactions.\n',
                                                                     'keywords': ['ipy', 'Agriculture', 'crop yield', 'maize', 'rice', 'soybean', 'wheat']}}},
                                     {'header': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786598',
                                                 'datestamp': '2022-11-11T13:47:55Z'},
                                      'metadata': {'pangeaDataset': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.786598',
                                                                     'authors': [{'author': {'lastName': 'Caruso', 'firstName': 'Tancredi', 'orcid': '0000-0002-3607-9609'}},
                                                                                 {'author': {'lastName': 'Borghini', 'firstName': 'Francesca', 'eMail': 'borghini@unisi.it'}},
                                                                                 {'author': {'lastName': 'Bucci', 'firstName': 'Charlie'}},
                                                                                 {'author': {'lastName': 'Colacevich', 'firstName': 'Andrea', 'eMail': 'colacevich2@unisi.it'}},
                                                                                 {'author': {'lastName': 'Bargagli', 'firstName': 'Roberto'}}],
                                                                     'title': 'Topsoil properties and abundance of Acari and Collembola species in northern Victoria Land, Antarctica', 'year': '2007',
                                                                     'technicalInfo': {'xmlLastModified': '2022-11-11T13:47:55Z',
                                                                                       'lastModified': '2017-08-08T07:09:25',
                                                                                       'filename': 'Caruso_2007',
                                                                                       'mimeType': 'application/zip',
                                                                                       'status': 'published',
                                                                                       'status_num': '4',
                                                                                       'DOIRegistryStatus': 'registered',
                                                                                       'DOIRegistryStatus_num': '4',
                                                                                       'DOIRegistrationDate': '2012-08-24T03:11:57',
                                                                                       'hierarchyLevel': 'parent',
                                                                                       'collectionType': 'publication series',
                                                                                       'collectionType_num': '4',
                                                                                       'collectionChilds': 'D786596,D786597',
                                                                                       'loginOption': 'unrestricted',
                                                                                       'loginOption_num': '1'},
                                                                     'setSpecs': ['citable', 'supplement', 'topicAgriculture', 'topicLithosphere'],
                                                                     'license': [{'license': {'label': 'CC-BY-3.0',
                                                                                                              'name': 'Creative Commons Attribution 3.0 Unported',
                                                                                                              'URI': 'https://creativecommons.org/licenses/by/3.0/'}}],
                                                                     'abstract': 'Soil fauna in the extreme conditions of Antarctica consists of a few microinvertebrate species patchily distributed at different spatial scales. Populations of the prostigmatic mite Stereotydeus belli and the collembolan Gressittacantha terranova from northern Victoria Land (Antarctica) were used as models to study the effect of soil properties on microarthropod distributions. In agreement with the general assumption that the development and distribution of life in these ecosystems is mainly controlled by abiotic factors, we found that the probability of occurrence of S. belli depends on soil moisture and texture and on the sampling period (which affects the general availability of water); surprisingly, none of the analysed variables were significantly related to the G. terranova distribution. Based on our results and literature data, we propose a theoretical model that introduces biotic interactions among the major factors driving the local distribution of collembolans in Antarctic terrestrial ecosystems.',
                                                                     'keywords': ['ipy']}}},
                                     {'header': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.787132',
                                                 'datestamp': '2022-11-11T13:44:22Z'},
                                      'metadata': {'pangeaDataset': {'identifier': 'oai:pangaea.de:doi:10.1594/PANGAEA.787132',
                                                                     'authors': [{'author': {'lastName': 'Kaiser', 'firstName': 'Knut', 'eMail': 'knut.kaiser@gfz-potsdam.de', 'orcid': '0000-0002-5080-6075'}},
                                                                                 {'author': {'lastName': 'Schoch', 'firstName': 'Werner H', 'orcid': '0000-0003-1364-0958'}},
                                                                                 {'author': {'lastName': 'Miehe', 'firstName': 'Georg', 'eMail': 'miehe@staff.uni-marburg.de'}}],
                                                                     'title': 'Granulometry, calcium carbonate content and radiocarbon ages of soil profiles obtained in Quinghai Province, northeast Tibet',
                                                                     'year': '2007',
                                                                     'technicalInfo': {'xmlLastModified': '2022-11-11T13:44:22Z',
                                                                                       'lastModified': '2017-08-08T07:09:24',
                                                                                       'filename': 'Kaiser_2007',
                                                                                       'mimeType': 'application/zip',
                                                                                       'status': 'published',
                                                                                       'status_num': '4',
                                                                                       'DOIRegistryStatus': 'registered',
                                                                                       'DOIRegistryStatus_num': '4',
                                                                                       'DOIRegistrationDate': '2012-09-12T03:11:26',
                                                                                       'hierarchyLevel': 'parent',
                                                                                       'collectionType': 'publication series',
                                                                                       'collectionType_num': '4',
                                                                                       'collectionChilds': 'D787129,D787131',
                                                                                       'loginOption': 'unrestricted',
                                                                                       'loginOption_num': '1'},
                                                                     'setSpecs': ['citable', 'supplement', 'topicAgriculture', 'topicLakesRivers', 'topicLithosphere'],
                                                                     'license': [{'license': {'label': 'CC-BY-3.0',
                                                                                                              'name': 'Creative Commons Attribution 3.0 Unported',
                                                                                                              'URI': 'https://creativecommons.org/licenses/by/3.0/'}}],
                                                                     'abstract': 'Colluvial deposits consisting of silts and loams were detected in several climatologically different areas of NE Tibet (3200-3700 m a.s.l.). Layering, distinct organic content and low content of coarse matter as well as location in the relief revealed an origin from low-energy slope erosion (hillwash). Underlying and intercalated paleosols were classified as Chernozems, Phaeozems, Regosols and Fluvisols. Fifteen radiocarbon datings predominant on charcoal from both colluvial layers and paleosols yielded ages between 8988 ± 66 and 3512 ± 56 uncal BP. Natural or anthropogenic factors could have been the triggers of the erosional processes derived. It remains unclear which reason was mainly responsible, due to controversial paleoclimatic and geomorphic records as well as insufficient archaeological knowledge from this region. Determinations of charcoal and fossil wood revealed the Holocene occurrence of tree species (spruce, juniper) for areas which nowadays have no trees or only few forest islands. Thus large areas of NE Tibet which are at present steppes and alpine pastures were forested in the past.',
                                                                     'keywords': []}}}]


pangea_all_datasets_list_response = [{'repository_name': 'PANGEA (Data Publisher for Earth & Environmental Science)', 'type': 'vdataset', 'source_metadata_created': '2009', 'source_metadata_modified': '', 'owner_org': 'pangea', 'author': 'Colacevich Andrea', 'author_email': '', 'doi': '10.1594/PANGAEA.786524', 'doi_date_published': '2009', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC-BY-3.0', 'license_title': 'Creative Commons Attribution 3.0 Unported', 'name': 'png-doi-10-1594-pangaea-786524', 'notes': 'Although soil algae are among the main primary producers in most terrestrial ecosystems of continental Antarctica, there are very few quantitative studies on their relative proportion in the main algal groups and on how their distribution is affected by biotic and abiotic factors. Such knowledge is essential for understanding the functioning of Antarctic terrestrial ecosystems. We therefore analyzed biological soil crusts from northern Victoria Land to determine their pH, electrical conductivity (EC), water content (W), total and organic C (TC and TOC) and total N (TN) contents, and the presence and abundance of photosynthetic pigments. In particular, the latter were tested as proxies for biomass and coarse-resolution community structure. Soil samples were collected from five sites with known soil algal communities and the distribution of pigments was shown to reflect differences in the relative proportions of Chlorophyta, Cyanophyta and Bacillariophyta in these sites. Multivariate and univariate models strongly indicated that almost all soil variables (EC, W, TOC and TN) were important environmental correlates of pigment distribution. However, a significant amount of variation is independent of these soil variables and may be ascribed to local variability such as changes in microclimate at varying spatial and temporal scales. There are at least five possible sources of local variation: pigment preservation, temporal variations in water availability, temporal and spatial interactions among environmental and biological components, the local-scale patchiness of organism distribution, and biotic interactions.\n', 'organization': {'approval_status': 'approved', 'description': 'PANGEA (Data Publisher for Earth & Environmental Science): The information system PANGAEA is operated as an Open Access library aimed at archiving, publishing and distributing georeferenced data from earth system research. PANGAEA guarantees long-term availability (greater than 10 years) of its content. PANGAEA is open to any project, institution, or individual scientist to use or to archive and publish data. PANGAEA focuses on georeferenced observational data, experimental data, and models/simulations. Citability, comprehensive metadata descriptions, interoperability of data and metadata, a high degree of structural and semantic harmonization of the data inventory as well as the commitment of the hosting institutions ensures FAIRness of archived data.', 'display_name': 'PANGEA', 'image_display_url': '/images/pangea-logo.png', 'image_url': '/images/pangea-logo.png', 'is_organization': True, 'name': 'pangea', 'state': 'active', 'title': 'PANGEA (Agriculture)', 'type': 'organization'}, 'title': 'Floral and faunal characteristics and content of photosynthetic pigment in soils of northern Victoria Land, Antarctica', 'url': 'https://doi.org/10.1594/PANGAEA.786524', 'orcid': '', 'extra_authors': [{'extra_author': 'Caruso Tancredi', 'orcid': '0000-0002-3607-9609'}, {'extra_author': 'Borghini Francesca', 'orcid': ''}, {'extra_author': 'Bargagli Roberto', 'orcid': ''}], 'tags': [{'display_name': 'ipy', 'name': 'ipy', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'Agriculture', 'name': 'Agriculture', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'crop yield', 'name': 'crop yield', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'maize', 'name': 'maize', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'rice', 'name': 'rice', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'soybean', 'name': 'soybean', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'wheat', 'name': 'wheat', 'state': 'active', 'vocabulary_id': None}], 'publication_year': '2009', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agriculture'}, {'subject_area_additional': '', 'subject_area_name': 'Lithosphere'}], 'resource_type': 'application/zip - filename: Colacevich_2009'},
                                     {'repository_name': 'PANGEA (Data Publisher for Earth & Environmental Science)', 'type': 'vdataset', 'source_metadata_created': '2007', 'source_metadata_modified': '', 'owner_org': 'pangea', 'author': 'Caruso Tancredi', 'author_email': '', 'doi': '10.1594/PANGAEA.786598', 'doi_date_published': '2007', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC-BY-3.0', 'license_title': 'Creative Commons Attribution 3.0 Unported', 'name': 'png-doi-10-1594-pangaea-786598', 'notes': 'Soil fauna in the extreme conditions of Antarctica consists of a few microinvertebrate species patchily distributed at different spatial scales. Populations of the prostigmatic mite Stereotydeus belli and the collembolan Gressittacantha terranova from northern Victoria Land (Antarctica) were used as models to study the effect of soil properties on microarthropod distributions. In agreement with the general assumption that the development and distribution of life in these ecosystems is mainly controlled by abiotic factors, we found that the probability of occurrence of S. belli depends on soil moisture and texture and on the sampling period (which affects the general availability of water); surprisingly, none of the analysed variables were significantly related to the G. terranova distribution. Based on our results and literature data, we propose a theoretical model that introduces biotic interactions among the major factors driving the local distribution of collembolans in Antarctic terrestrial ecosystems.', 'organization': {'approval_status': 'approved', 'description': 'PANGEA (Data Publisher for Earth & Environmental Science): The information system PANGAEA is operated as an Open Access library aimed at archiving, publishing and distributing georeferenced data from earth system research. PANGAEA guarantees long-term availability (greater than 10 years) of its content. PANGAEA is open to any project, institution, or individual scientist to use or to archive and publish data. PANGAEA focuses on georeferenced observational data, experimental data, and models/simulations. Citability, comprehensive metadata descriptions, interoperability of data and metadata, a high degree of structural and semantic harmonization of the data inventory as well as the commitment of the hosting institutions ensures FAIRness of archived data.', 'display_name': 'PANGEA', 'image_display_url': '/images/pangea-logo.png', 'image_url': '/images/pangea-logo.png', 'is_organization': True, 'name': 'pangea', 'state': 'active', 'title': 'PANGEA (Agriculture)', 'type': 'organization'}, 'title': 'Topsoil properties and abundance of Acari and Collembola species in northern Victoria Land, Antarctica', 'url': 'https://doi.org/10.1594/PANGAEA.786598', 'orcid': '0000-0002-3607-9609', 'extra_authors': [{'extra_author': 'Borghini Francesca', 'orcid': ''}, {'extra_author': 'Bucci Charlie', 'orcid': ''}, {'extra_author': 'Colacevich Andrea', 'orcid': ''}, {'extra_author': 'Bargagli Roberto', 'orcid': ''}], 'tags': [{'display_name': 'ipy', 'name': 'ipy', 'state': 'active', 'vocabulary_id': None}], 'publication_year': '2007', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agriculture'}, {'subject_area_additional': '', 'subject_area_name': 'Lithosphere'}], 'resource_type': 'application/zip - filename: Caruso_2007'},
                                     {'repository_name': 'PANGEA (Data Publisher for Earth & Environmental Science)', 'type': 'vdataset', 'source_metadata_created': '2007', 'source_metadata_modified': '', 'owner_org': 'pangea', 'author': 'Kaiser Knut', 'author_email': '', 'doi': '10.1594/PANGAEA.787132', 'doi_date_published': '2007', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC-BY-3.0', 'license_title': 'Creative Commons Attribution 3.0 Unported', 'name': 'png-doi-10-1594-pangaea-787132', 'notes': 'Colluvial deposits consisting of silts and loams were detected in several climatologically different areas of NE Tibet (3200-3700 m a.s.l.). Layering, distinct organic content and low content of coarse matter as well as location in the relief revealed an origin from low-energy slope erosion (hillwash). Underlying and intercalated paleosols were classified as Chernozems, Phaeozems, Regosols and Fluvisols. Fifteen radiocarbon datings predominant on charcoal from both colluvial layers and paleosols yielded ages between 8988 ± 66 and 3512 ± 56 uncal BP. Natural or anthropogenic factors could have been the triggers of the erosional processes derived. It remains unclear which reason was mainly responsible, due to controversial paleoclimatic and geomorphic records as well as insufficient archaeological knowledge from this region. Determinations of charcoal and fossil wood revealed the Holocene occurrence of tree species (spruce, juniper) for areas which nowadays have no trees or only few forest islands. Thus large areas of NE Tibet which are at present steppes and alpine pastures were forested in the past.', 'organization': {'approval_status': 'approved', 'description': 'PANGEA (Data Publisher for Earth & Environmental Science): The information system PANGAEA is operated as an Open Access library aimed at archiving, publishing and distributing georeferenced data from earth system research. PANGAEA guarantees long-term availability (greater than 10 years) of its content. PANGAEA is open to any project, institution, or individual scientist to use or to archive and publish data. PANGAEA focuses on georeferenced observational data, experimental data, and models/simulations. Citability, comprehensive metadata descriptions, interoperability of data and metadata, a high degree of structural and semantic harmonization of the data inventory as well as the commitment of the hosting institutions ensures FAIRness of archived data.', 'display_name': 'PANGEA', 'image_display_url': '/images/pangea-logo.png', 'image_url': '/images/pangea-logo.png', 'is_organization': True, 'name': 'pangea', 'state': 'active', 'title': 'PANGEA (Agriculture)', 'type': 'organization'}, 'title': 'Granulometry, calcium carbonate content and radiocarbon ages of soil profiles obtained in Quinghai Province, northeast Tibet', 'url': 'https://doi.org/10.1594/PANGAEA.787132', 'orcid': '0000-0002-5080-6075', 'extra_authors': [{'extra_author': 'Schoch Werner H', 'orcid': '0000-0003-1364-0958'}, {'extra_author': 'Miehe Georg', 'orcid': ''}], 'publication_year': '2007', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agriculture'}, {'subject_area_additional': '', 'subject_area_name': 'LakesRivers'}, {'subject_area_additional': '', 'subject_area_name': 'Lithosphere'}], 'resource_type': 'application/zip - filename: Kaiser_2007'}]

ckan_dict_of_imported_dataset = {
        "author": "Caruso Tancredi",
        "author_email": "",
        "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
        "doi": "10.1594/PANGAEA.786598",
        "doi_date_published": "2007",
        "doi_publisher": "",
        "doi_status": "True",
        "id": "c7c0149f-a2ea-4287-a0f4-4ab3084c56ad",
        "isopen": False,
        "license_id": "CC-BY-3.0",
        "license_title": "CC-BY-3.0",
        "metadata_created": "2022-12-01T10:45:31.295555",
        "metadata_modified": "2022-12-01T10:45:31.295564",
        "name": "png-doi-10-1594-pangaea-786598",
        "notes": "Soil fauna in the extreme conditions of Antarctica consists of a few microinvertebrate species patchily distributed at different spatial scales. Populations of the prostigmatic mite Stereotydeus belli and the collembolan Gressittacantha terranova from northern Victoria Land (Antarctica) were used as models to study the effect of soil properties on microarthropod distributions. In agreement with the general assumption that the development and distribution of life in these ecosystems is mainly controlled by abiotic factors, we found that the probability of occurrence of S. belli depends on soil moisture and texture and on the sampling period (which affects the general availability of water); surprisingly, none of the analysed variables were significantly related to the G. terranova distribution. Based on our results and literature data, we propose a theoretical model that introduces biotic interactions among the major factors driving the local distribution of collembolans in Antarctic terrestrial ecosystems.",
        "num_resources": 0,
        "num_tags": 1,
        "orcid": "0000-0002-3607-9609",
        "organization": {
            "id": "225dae62-f177-4c9d-a700-85977704be1f",
            "name": "pangea",
            "title": "PANGEA (Agriculture)",
            "type": "organization",
            "description": "PANGEA (Data Publisher for Earth & Environmental Science): The information system PANGAEA is operated as an Open Access library aimed at archiving, publishing and distributing georeferenced data from earth system research. PANGAEA guarantees long-term availability (greater than 10 years) of its content. PANGAEA is open to any project, institution, or individual scientist to use or to archive and publish data. PANGAEA focuses on georeferenced observational data, experimental data, and models/simulations. Citability, comprehensive metadata descriptions, interoperability of data and metadata, a high degree of structural and semantic harmonization of the data inventory as well as the commitment of the hosting institutions ensures FAIRness of archived data.",
            "image_url": "/images/pangea-logo.png",
            "created": "2022-12-01T11:22:53.820115",
            "is_organization": True,
            "approval_status": "approved",
            "state": "active"
        },
        "owner_org": "225dae62-f177-4c9d-a700-85977704be1f",
        "private": False,
        "publication_year": "2007",
        "repository_name": "PANGEA (Data Publisher for Earth & Environmental Science)",
        "resource_type": "application/zip - filename: Caruso_2007",
        "source_metadata_created": "2007",
        "source_metadata_modified": "",
        "state": "active",
        "title": "Topsoil properties and abundance of Acari and Collembola species in northern Victoria Land, Antarctica",
        "type": "vdataset",
        "url": "https://doi.org/10.1594/PANGAEA.786598",
        "extra_authors": [
            {
                "extra_author": "Borghini Francesca",
                "orcid": ""
            },
            {
                "extra_author": "Bucci Charlie",
                "orcid": ""
            },
            {
                "extra_author": "Colacevich Andrea",
                "orcid": ""
            },
            {
                "extra_author": "Bargagli Roberto",
                "orcid": ""
            }
        ],
        "subject_areas": [
            {
                "subject_area_additional": "",
                "subject_area_name": "Agriculture"
            },
            {
                "subject_area_additional": "",
                "subject_area_name": "Lithosphere"
            }
        ],
        "tags": [
            {
                "display_name": "ipy",
                "id": "1ab15c2f-caa9-4a10-80df-ac9f23ecf834",
                "name": "ipy",
                "state": "active",
                "vocabulary_id": None
            }
        ],
        "resources": [],
        "groups": [],
        "relationships_as_subject": [],
        "relationships_as_object": []
    }


pangea_dict_of_imported_dataset = pangea_all_datasets_list_response[1]