# LOCAL CKAN DATA
# ***************
local_organization_data = {'approval_status': 'approved',
                                'created': '2021-07-22T14:33:24.825599',
                                'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                'display_name': 'TIB',
                                'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                'image_display_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                'is_organization': True,
                                'name': 'tib-iasis',
                                'num_followers': 0,
                                'state': 'active',
                                'title': 'TIB',
                                'type': 'organization',
                                'tags': []}


local_dataset_data = {'author': 'Autodesk',
                      'author_email': '',
                      'creator_user_id': '6114fb41-d314-4c35-b8c1-278c9f997579',
                      'id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                      'isopen': True,
                      'license_id': 'cc-by',
                      'license_title': 'Creative Commons Attribution',
                      'license_url': 'http://www.opendefinition.org/licenses/cc-by',
                      'maintainer': '',
                      'maintainer_email': '',
                      'metadata_created': '2021-07-26T06:19:07.491127',
                      'metadata_modified': '2021-07-26T06:19:07.491139',
                      'name': 'example-cad',
                      'notes': 'Example usage of CAD visualization in 2D and 3D using CKAN Views.',
                      'num_resources': 2,
                      'num_tags': 0,
                      'organization': {'id': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                                       'name': 'tib-iasis',
                                       'title': 'TIB',
                                       'type': 'organization',
                                       'description': 'The German National Library of Science and Technology, abbreviated TIB, is the national library of the Federal Republic of Germany for all fields of engineering, technology, and the natural sciences.',
                                       'image_url': 'https://www.tib.eu/typo3conf/ext/tib_tmpl_bootstrap/Resources/Public/images/TIB_Logo_en.png',
                                       'created': '2021-07-22T14:33:24.825599',
                                       'is_organization': True,
                                       'approval_status': 'approved',
                                       'state': 'active'},
                      'owner_org': '0c5362f5-b99e-41db-8256-3d0d7549bf4d',
                      'private': False,
                      'state': 'active',
                      'title': 'Example CAD',
                      'type': 'dataset',
                      'url': 'https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html',
                      'version': '',
                      'extras': [{'key': 'foobar', 'value': 'baz'}],
                      'resources': [{'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:37:19.897441',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '4ee0ec1c-c72b-4bad-be73-364a735cea5c',
                                     'last_modified': '2017-12-01T16:52:30.511835',
                                     'metadata_modified': '2021-07-26T05:23:45.398718',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 2D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 0,
                                     'resource_type': None,
                                     'size': 169807,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/Drive_shaft.dwg',
                                     'url_type': ''},
                                    {'cache_last_updated': None,
                                     'cache_url': None,
                                     'created': '2017-11-23T17:40:23.217872',
                                     'datastore_active': False,
                                     'description': '',
                                     'format': '',
                                     'hash': '',
                                     'id': '1342ec64-f18e-4860-93cc-f6dd194d56ec',
                                     'last_modified': '2017-12-01T16:53:23.693615',
                                     'metadata_modified': '2021-07-26T05:23:45.401967',
                                     'mimetype': None,
                                     'mimetype_inner': None,
                                     'name': 'Example 3D .dwg file',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'position': 1,
                                     'resource_type': None,
                                     'size': 733036,
                                     'state': 'active',
                                     'url': 'https://github.com/guillermobet/files/raw/master/visualization_-_aerial.dwg',
                                     'url_type': ''}],
                      'tags': [],
                      'groups': [],
                      'relationships_as_subject': [],
                      'relationships_as_object': []}

# RADAR API DATA
# ***************


radar_dataset_parsed_to_dict = {'header': {'identifier': '10.22000/152X',
                                           'datestamp': '2022-04-04T09:06:49Z'},
                                'metadata': {'radarDataset': {'identifier': {'identifier': '10.22000/152X',
                                                                             'identifierType': 'DOI'},
                                                              'creators': [{'creator': {'creatorName': 'Schughart, Klaus',
                                                                                        'givenName': 'Klaus',
                                                                                        'familyName': 'Schughart',
                                                                                        'creatorAffiliation': 'Helmholtz Centre for Infection Research',
                                                                                        'nameIdentifier': {'nameIdentifier': '0000-0002-6824-7523',
                                                                                                           'schemeURI': 'http://orcid.org/',
                                                                                                           'nameIdentifierScheme': 'ORCID'}}},
                                                                           {'creator': {'creatorName': 'Mayer, Manfred',
                                                                                        'givenName': 'Manfred',
                                                                                        'familyName': 'Mayer',
                                                                                        'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)',
                                                                                        'nameIdentifier': {'nameIdentifier': '0000-0002-6382-2533',
                                                                                                           'schemeURI': 'http://orcid.org/',
                                                                                                           'nameIdentifierScheme': 'ORCID'}}},
                                                                           {'creator': {'creatorName': 'Reinsch, Norbert',
                                                                                        'givenName': 'Norbert',
                                                                                        'familyName': 'Reinsch',
                                                                                        'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)',
                                                                                        'nameIdentifier': {'nameIdentifier': '0000-0001-7435-4088',
                                                                                                           'schemeURI': 'http://orcid.org/',
                                                                                                           'nameIdentifierScheme': 'ORCID'}}}],
                                                              'title': 'data and codes for publication Tang et al 2019',
                                                              'publishers': [{'publisher': {'publisher': 'Klaus Schughart'}},
                                                                             {'publisher': {'publisher': 'Putnings, Markus'}}],
                                                              'productionYear': '2019',
                                                              'publicationYear': '2019',
                                                              'subjectAreas': [{'subjectArea': {'controlledSubjectAreaName': 'Medicine'}},
                                                                               {'subjectArea': {'controlledSubjectAreaName': 'Other',
                                                                                                'additionalSubjectAreaName': 'Bibliotheks- und Informationswissenschaft'}}],
                                                              'resource': {'resource': 'Data and R codes',
                                                                           'resourceType': 'Dataset'},
                                                              'rights': [{'rights': {'controlledRights': 'CC BY 4.0 Attribution',
                                                                                     'additionalRights': 'Licenses of the images according to image_licenses.csv'}}],
                                                              'rightsHolders': [{'rightsHolder': {'rightsHolder': 'Klaus Schughart'}},
                                                                                {'rightsHolder': {'rightsHolder': 'Springstein, Matthias'}},
                                                                                {'rightsHolder': {'rightsHolder': 'Ewerth, Ralph'}}],
                                                              'additionalTitles': [{'additionalTitle': {'additionalTitle': 'Supplementary Data PhD Thesis'},
                                                                                    'additionalTitleType': 'Subtitle'},
                                                                                   {'additionalTitle': {'additionalTitle': 'Supplementary Data PhD Thesis'},
                                                                                    'additionalTitleType': 'Subtitle'}],
                                                              'descriptions': [{'description': {'description': 'The dataset contains the data underlying the plots and histograms in the article "Collective photon emission patterns from two atoms in free space". The data show the photon statistics of a trapped two-ion crystal observed in the far-field.  Details of the measurement process and experimental setup can be found in the journal publication. The data for each individual plot are presented as a table in a separate sheet in an xlsx-spreadsheet.'},
                                                                                'descriptionType': 'Abstract'},
                                                                               {'description': {'description': 'Interviewtranskripte, Fragebogenauswertungen'},
                                                                                'descriptionType': 'Other'}],
                                                              'keywords': [{'keyword': {'keyword': 'downy mildew resistance'}},
                                                                           {'keyword': {'keyword': 'untargeted metabolomics'}},
                                                                           {'keyword': {'keyword': 'genome-wide association study'}},
                                                                           {'keyword': {'keyword': 'phenylpropanoids'}},
                                                                           {'keyword': {'keyword': 'hop'}},
                                                                           {'keyword': {'keyword': 'oomycete'}}],
                                                              'contributors': [{'contributor': {'contributorName': 'Pohl, Ernst',
                                                                                                'givenName': 'Ernst',
                                                                                                'familyName': 'Pohl',
                                                                                                'contributorAffiliation': 'Universität Bonn, Institut für Archäologie und Kulturanthropologie, Abteilung Vor- und Frühgeschichtliche Archäologie'}},
                                                                               {'contributor': {'contributorName': 'Przemuß, Ivonne',
                                                                                                'givenName': 'Ivonne',
                                                                                                'familyName': 'Przemuß',
                                                                                                'contributorAffiliation': 'Friedrich-Schiller-Universität Jena, Institut für Orientalistik, Indogermanistik und Ur- und Frühgeschichtliche Archäologie, Seminar für Ur- und Frühgeschichtliche Archäologie',
                                                                                                'nameIdentifier': {'nameIdentifier': '0000-0002-5168-4540',
                                                                                                                   'schemeURI': 'http://orcid.org/',
                                                                                                                   'nameIdentifierScheme': 'ORCID'}}}],
                                                              'language': 'eng',
                                                              'alternateIdentifiers': [{'alternateIdentifier': {'alternateIdentifier': 'MN729603'},
                                                                                        'alternateIdentifierType': 'GenBank accession number'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': '111830-76-3'},
                                                                                        'alternateIdentifierType': 'CAS Registry Number'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': 'InChI=1S/C33H44N7O19P3S/c1-33(2,28(44)31(45)36-10-9-23(41)35-11-12-63-24(42)6-4-3-5-19-7-8-20-21(13-19)54-18-53-20)15-56-62(51,52)59-61(49,50)55-14-22-27(58-60(46,47)48)26(43)32(57-22)40-17-39-25-29(34)37-16-38-30(25)40/h3-8,13,16-17,22,26-28,32,43-44H,9-12,14-15,18H2,1-2H3,(H,35,41)(H,36,45)(H,49,50)(H,51,52)(H2,34,37,38)(H2,46,47,48)/b5-3+,6-4+/t22-,26+,27+,28-,32-/m1/s1'},
                                                                                        'alternateIdentifierType': 'InChI'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': 'GEVZCNXLEOONCV-RJPWVWRHSA-N'},
                                                                                        'alternateIdentifierType': 'InChIKey'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': '123022-35-5'},
                                                                                        'alternateIdentifierType': 'CAS Registry Number'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': 'InChI=1S/C12H12O4/c1-16-11-8-9(6-7-10(11)13)4-2-3-5-12(14)15/h2-8,13H,1H3,(H,14,15)/b4-2+,5-3+'},
                                                                                        'alternateIdentifierType': 'InChI'},
                                                                                       {'alternateIdentifier': {'alternateIdentifier': 'PZTHQMWVDHEWPY-ZUVMSYQZSA-N'},
                                                                                        'alternateIdentifierType': 'InChIKey'}],
                                                              'relatedIdentifiers': [{'relatedIdentifier': {'relatedIdentifier': '10.1111/tpj.14652'},
                                                                                      'relatedIdentifierType': 'DOI',
                                                                                      'relationType': 'IsSupplementTo'},
                                                                                     {'relatedIdentifier': {'relatedIdentifier': '10.5452/ma-2bzsh'},
                                                                                      'relatedIdentifierType': 'DOI',
                                                                                      'relationType': 'References'}],
                                                              'geoLocations': [{'geoLocation': {'geoLocationCountry': 'GERMANY',
                                                                                                'geoLocationRegion': 'North-Rhine Westphalia, Rhineland-Platinate',
                                                                                                'geoLocationPoint': '00000',
                                                                                                'geoLocationBox': '11111'}}],
                                                              'dataSources': [{'dataSource': {'dataSource': 'Waters e2695 chromatography workstation with photodiode array detector (PDA) and a QDA mass detector (Waters)'},
                                                                               'dataSourceDetail': 'Instrument'},
                                                                              {'dataSource': {'dataSource': 'BioRad CFX ConnectTM Real-Time System'},
                                                                               'dataSourceDetail': 'Instrument'}],
                                                              'software': [{'softwareType': {'softwareName': {'softwareName': 'Microsoft Office',
                                                                                                              'softwareVersion': '2013'}}},
                                                                           {'softwareType': {'softwareName': {'softwareName': 'Waters Empower',
                                                                                                              'softwareVersion': '3'},
                                                                                             'alternativeSoftwareName': {'alternativeSoftwareName': 'R',
                                                                                                                         'alternativeSoftwareVersion': '3.6.2'}}}],
                                                              'processing': [{'dataProcessing': {'dataProcessing': 'Kollisionsdetektion'}}],
                                                              'relatedInformations': [{'relatedInformation': {'relatedInformation': 'DOI Journal Article'},
                                                                                       'relatedInformationType': '10.1038/s42003-021-01967-9'}],
                                                              'fundingReferences': [{'fundingReference': {'funderName': 'Landwirtschaftliche Rentenbank',
                                                                                                          'funderIdentifier': {'funderIdentifier': 'Project No. 182849149 (SFB 953)', 'type': 'Other'},
                                                                                                          'awardNumber': 'UBO 53C-50009_00_71030002',
                                                                                                          'awardURI': 'https://gepris.dfg.de/gepris/projekt/318064602',
                                                                                                          'awardTitle': 'Biosynthese der Piperamide im schwarzen Pfeffer (Piper nigrum)'}}]}}}


radar_dataset_parsed_to_ckan_dict = {'repository_name': 'RADAR (Research Data Repository)',
                                     'type': 'vdataset',
                                     'source_metadata_created': '2019',
                                     'source_metadata_modified': '',
                                     'owner_org': 'radar',
                                     'author': 'Schughart, Klaus',
                                     'author_email': '',
                                     'doi': '10.22000/152X',
                                     'doi_date_published': '2019',
                                     'doi_publisher': '',
                                     'doi_status': 'True',
                                     'license_id': 'CC BY 4.0 Attribution',
                                     'license_title': 'Licenses of the images according to image_licenses.csv',
                                     'name': 'rdr-doi-10-22000-152x',
                                     'notes': 'Abstract: The dataset contains the data underlying the plots and histograms in the article "Collective photon emission patterns from two atoms in free space". The data show the photon statistics of a trapped two-ion crystal observed in the far-field.  Details of the measurement process and experimental setup can be found in the journal publication. The data for each individual plot are presented as a table in a separate sheet in an xlsx-spreadsheet.\r\nOther: Interviewtranskripte, Fragebogenauswertungen',
                                     'organization': {'approval_status': 'approved',
                                                      'description': 'RADAR (Research Data Repository) is a cross-disciplinary repository for archiving and publishing research data from completed scientific studies and projects. The focus is on research data from subjects that do not yet have their own discipline-specific infrastructures for research data management. ',
                                                      'display_name': 'RADAR',
                                                      'image_display_url': '/images/radar-logo.png',
                                                      'image_url': '/images/radar-logo.png',
                                                      'is_organization': True,
                                                      'name': 'radar',
                                                      'state': 'active',
                                                      'title': 'RADAR',
                                                      'type': 'organization'},
                                     'title': 'Data and codes for publication tang et al 2019',
                                     'url': 'https://doi.org/10.22000/152X',
                                     'orcid': '0000-0002-6824-7523',
                                     'extra_authors': [{'extra_author': 'Mayer, Manfred',
                                                        'orcid': '0000-0002-6382-2533'},
                                                       {'extra_author': 'Reinsch, Norbert',
                                                        'orcid': '0000-0001-7435-4088'}],
                                     'tags': [{'display_name': 'downy mildew resistance',
                                               'name': 'downy mildew resistance',
                                               'state': 'active',
                                               'vocabulary_id': None},
                                              {'display_name': 'untargeted metabolomics',
                                               'name': 'untargeted metabolomics',
                                               'state': 'active',
                                               'vocabulary_id': None},
                                              {'display_name': 'genome-wide association study',
                                               'name': 'genome-wide association study',
                                               'state': 'active',
                                               'vocabulary_id': None},
                                              {'display_name': 'phenylpropanoids',
                                               'name': 'phenylpropanoids',
                                               'state': 'active',
                                               'vocabulary_id': None},
                                              {'display_name': 'hop',
                                               'name': 'hop',
                                               'state': 'active',
                                               'vocabulary_id': None},
                                              {'display_name': 'oomycete',
                                               'name': 'oomycete',
                                               'state': 'active',
                                               'vocabulary_id': None}],
                                     'publishers': [{'publisher': 'Klaus Schughart'},
                                                    {'publisher': 'Putnings, Markus'}],
                                     'production_year': '2019',
                                     'publication_year': '2019',
                                     'subject_areas': [{'subject_area_additional': '',
                                                        'subject_area_name': 'Medicine'},
                                                       {'subject_area_additional': 'Bibliotheks- und Informationswissenschaft',
                                                        'subject_area_name': 'Other'}],
                                     'resource_type': 'Dataset - Data and R codes'}


LDM_imported_dataset = {
        "author": "Clemens Huebler",
        "author_email": "c.huebler@isd.uni-hannover.de",
        "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
        "doi": "10.25835/0078042",
        "doi_date_published": "2020-06-29",
        "doi_publisher": "LUIS",
        "doi_status": "True",
        "domain": "https://data.uni-hannover.de",
        "have_copyright": "Yes",
        "id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
        "isopen": False,
        "license_id": "CC-BY-3.0",
        "license_title": "CC-BY-3.0",
        "maintainer": "Clemens Huebler",
        "maintainer_email": "c.huebler@isd.uni-hannover.de",
        "metadata_created": "2021-10-07T09:58:55.243407",
        "metadata_modified": "2021-10-07T09:58:55.243416",
        "name": "luh-windturbine-simulation-for-meta-modelling",
        "notes": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).\r\nFor further information, it is referred to \"Huebler, C., & Rolfes, R. (2020). Analysis of the influence of climate change on the fatigue lifetime of offshore wind turbines using imprecise probabilities. Wind Energy. 2020;1–15.\"",
        "num_resources": 2,
        "num_tags": 3,
        "organization": {
            "id": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
            "name": "institut-fur-statik-und-dynamik",
            "title": "Institut für Statik und Dynamik",
            "type": "organization",
            "description": "(Institute of Structural Analysis) \r\nAppelstraße 9A \r\n__30167 Hannover (Germany)__\r\n\r\nhttps://www.isd.uni-hannover.de/en/institute/",
            "image_url": "",
            "created": "2021-10-07T11:46:15.762388",
            "is_organization": True,
            "approval_status": "approved",
            "state": "active"
        },
        "owner_org": "3d4e7da1-a0ef-4af1-9c07-56cf5e35084d",
        "private": False,
        "repository_name": "Leibniz University Hannover",
        "services_used_list": "",
        "source_metadata_created": "2020-06-29T13:56:20.726566",
        "source_metadata_modified": "2021-07-06T09:21:41.322946",
        "state": "active",
        "terms_of_usage": "Yes",
        "title": "Wind Turbine Simulation Data for Meta-Modelling",
        "type": "vdataset",
        "url": "https://data.uni-hannover.de/dataset/windturbine-simulation-for-meta-modelling",
        "version": "",
        "resources": [
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:56:24.253776",
                "datastore_active": False,
                "description": "",
                "downloadall_datapackage_hash": "98b5bd1da7a98e0a79ab9dae7e68f8cd",
                "downloadall_metadata_modified": "2021-07-06T09:21:25.079814",
                "format": "ZIP",
                "hash": "",
                "id": "da3a4b40-c6b3-42de-87a4-4ea60c441910",
                "last_modified": "2021-07-06T09:21:36.339262",
                "metadata_modified": "2021-10-07T09:58:55.231269",
                "mimetype": "application/zip",
                "mimetype_inner": None,
                "name": "All resource data",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 0,
                "resource_type": None,
                "revision_id": "5b858701-baff-4dff-86a8-06cb0c01f224",
                "size": 875,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/da3a4b40-c6b3-42de-87a4-4ea60c441910/download/windturbine-simulation-for-meta-modelling-otpq81.zip",
                "url_type": ""
            },
            {
                "cache_last_updated": None,
                "cache_url": None,
                "created": "2020-06-29T13:59:45.579275",
                "datastore_active": False,
                "description": "This data set correlates environmental conditions acting on an offshore wind turbine (inputs) with fatigue loads of the turbine (outputs).\r\nThe investigated wind turbine is the NREL 5MW reference turbine and the OC3 monopile.\r\nEnvironmental conditions are based on FINO3 data (https://www.fino3.de/en/).\r\nTime series of bending moments and shear forces at mudline and blade root bending moments are computed using the FASTv8 simulation code by the NREL.\r\n10.000 simulations for varying environmental conditions (and varying random seeds) were conducted.\r\nShort-term damage equivalent loads (DELs) representing fatigue were calculated for several relevant positions (at mudline and at the blade root).",
                "format": "TXT",
                "hash": "",
                "id": "0f24dea1-53b3-4cb9-afa4-16b342524aa8",
                "last_modified": "2020-06-29T13:59:45.533215",
                "metadata_modified": "2021-10-07T09:58:55.233372",
                "mimetype": "text/plain",
                "mimetype_inner": None,
                "name": "Metamodeldata.txt",
                "package_id": "7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3",
                "position": 1,
                "resource_type": None,
                "revision_id": "f5dad358-82bc-44cd-84a8-5f68f14a774e",
                "size": 1142901,
                "state": "active",
                "url": "https://data.uni-hannover.de/dataset/7e6929b4-0aa0-44b4-9a1c-29d42bb78aa3/resource/0f24dea1-53b3-4cb9-afa4-16b342524aa8/download/metamodeldata.txt",
                "url_type": ""
            }
        ],
        "tags": [
            {
                "display_name": "FAST",
                "id": "235ed4d9-3def-4174-bb4d-51950abe8813",
                "name": "FAST",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "meta-model",
                "id": "2c83feeb-a00e-4821-91b1-c42fb828a3ad",
                "name": "meta-model",
                "state": "active",
                "vocabulary_id": None
            },
            {
                "display_name": "wind energy",
                "id": "81223f1d-955d-4ff4-8be0-1fda56b540ba",
                "name": "wind energy",
                "state": "active",
                "vocabulary_id": None
            }
        ],
        "groups": [],
        "relationships_as_subject": [],
        "relationships_as_object": []
    }

resumption_token_ok = {'resumptionToken': 'rows=100@@searchMark=10.22000/72@@from=0001-01-01T00:00:00Z@@total=179@@until=9999-12-31T23:59:59Z@@metadataPrefix=radar', 'completeListSize': '179'}

resumption_token_empty = {'resumptionToken': ''}

expected_list_of_dict_from_radar = [{'header': {'identifier': '10.22000/152X', 'datestamp': '2022-04-04T09:06:49Z'}, 'metadata': {'radarDataset': {'identifier': {'identifier': '10.22000/152X', 'identifierType': 'DOI'}, 'creators': [{'creator': {'creatorName': 'Schughart, Klaus', 'givenName': 'Klaus', 'familyName': 'Schughart', 'creatorAffiliation': 'Helmholtz Centre for Infection Research', 'nameIdentifier': {'nameIdentifier': '0000-0002-6824-7523', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}, {'creator': {'creatorName': 'Mayer, Manfred', 'givenName': 'Manfred', 'familyName': 'Mayer', 'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)', 'nameIdentifier': {'nameIdentifier': '0000-0002-6382-2533', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}, {'creator': {'creatorName': 'Reinsch, Norbert', 'givenName': 'Norbert', 'familyName': 'Reinsch', 'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)', 'nameIdentifier': {'nameIdentifier': '0000-0001-7435-4088', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}], 'title': 'data and codes for publication Tang et al 2019', 'publishers': [{'publisher': {'publisher': 'Klaus Schughart'}}, {'publisher': {'publisher': 'Putnings, Markus'}}], 'productionYear': '2019', 'publicationYear': '2019', 'subjectAreas': [{'subjectArea': {'controlledSubjectAreaName': 'Medicine'}}, {'subjectArea': {'controlledSubjectAreaName': 'Other', 'additionalSubjectAreaName': 'Bibliotheks- und Informationswissenschaft'}}], 'resource': {'resource': 'Data and R codes', 'resourceType': 'Dataset'}, 'rights': [{'rights': {'controlledRights': 'CC BY 4.0 Attribution', 'additionalRights': 'Licenses of the images according to image_licenses.csv'}}], 'rightsHolders': [{'rightsHolder': {'rightsHolder': 'Klaus Schughart'}}, {'rightsHolder': {'rightsHolder': 'Springstein, Matthias'}}, {'rightsHolder': {'rightsHolder': 'Ewerth, Ralph'}}], 'additionalTitles': [{'additionalTitle': {'additionalTitle': 'Supplementary Data PhD Thesis'}, 'additionalTitleType': 'Subtitle'}, {'additionalTitle': {'additionalTitle': 'Supplementary Data PhD Thesis'}, 'additionalTitleType': 'Subtitle'}], 'descriptions': [{'description': {'description': 'The dataset contains the data underlying the plots and histograms in the article "Collective photon emission patterns from two atoms in free space". The data show the photon statistics of a trapped two-ion crystal observed in the far-field.  Details of the measurement process and experimental setup can be found in the journal publication. The data for each individual plot are presented as a table in a separate sheet in an xlsx-spreadsheet.'}, 'descriptionType': 'Abstract'}, {'description': {'description': 'Interviewtranskripte, Fragebogenauswertungen'}, 'descriptionType': 'Other'}], 'keywords': [{'keyword': {'keyword': 'downy mildew resistance'}}, {'keyword': {'keyword': 'untargeted metabolomics'}}, {'keyword': {'keyword': 'genome-wide association study'}}, {'keyword': {'keyword': 'phenylpropanoids'}}, {'keyword': {'keyword': 'hop'}}, {'keyword': {'keyword': 'oomycete'}}], 'contributors': [{'contributor': {'contributorName': 'Pohl, Ernst', 'givenName': 'Ernst', 'familyName': 'Pohl', 'contributorAffiliation': 'Universität Bonn, Institut für Archäologie und Kulturanthropologie, Abteilung Vor- und Frühgeschichtliche Archäologie'}}, {'contributor': {'contributorName': 'Przemuß, Ivonne', 'givenName': 'Ivonne', 'familyName': 'Przemuß', 'contributorAffiliation': 'Friedrich-Schiller-Universität Jena, Institut für Orientalistik, Indogermanistik und Ur- und Frühgeschichtliche Archäologie, Seminar für Ur- und Frühgeschichtliche Archäologie', 'nameIdentifier': {'nameIdentifier': '0000-0002-5168-4540', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}], 'language': 'eng', 'alternateIdentifiers': [{'alternateIdentifier': {'alternateIdentifier': 'MN729603'}, 'alternateIdentifierType': 'GenBank accession number'}, {'alternateIdentifier': {'alternateIdentifier': '111830-76-3'}, 'alternateIdentifierType': 'CAS Registry Number'}, {'alternateIdentifier': {'alternateIdentifier': 'InChI=1S/C33H44N7O19P3S/c1-33(2,28(44)31(45)36-10-9-23(41)35-11-12-63-24(42)6-4-3-5-19-7-8-20-21(13-19)54-18-53-20)15-56-62(51,52)59-61(49,50)55-14-22-27(58-60(46,47)48)26(43)32(57-22)40-17-39-25-29(34)37-16-38-30(25)40/h3-8,13,16-17,22,26-28,32,43-44H,9-12,14-15,18H2,1-2H3,(H,35,41)(H,36,45)(H,49,50)(H,51,52)(H2,34,37,38)(H2,46,47,48)/b5-3+,6-4+/t22-,26+,27+,28-,32-/m1/s1'}, 'alternateIdentifierType': 'InChI'}, {'alternateIdentifier': {'alternateIdentifier': 'GEVZCNXLEOONCV-RJPWVWRHSA-N'}, 'alternateIdentifierType': 'InChIKey'}, {'alternateIdentifier': {'alternateIdentifier': '123022-35-5'}, 'alternateIdentifierType': 'CAS Registry Number'}, {'alternateIdentifier': {'alternateIdentifier': 'InChI=1S/C12H12O4/c1-16-11-8-9(6-7-10(11)13)4-2-3-5-12(14)15/h2-8,13H,1H3,(H,14,15)/b4-2+,5-3+'}, 'alternateIdentifierType': 'InChI'}, {'alternateIdentifier': {'alternateIdentifier': 'PZTHQMWVDHEWPY-ZUVMSYQZSA-N'}, 'alternateIdentifierType': 'InChIKey'}], 'relatedIdentifiers': [{'relatedIdentifier': {'relatedIdentifier': '10.1111/tpj.14652'}, 'relatedIdentifierType': 'DOI', 'relationType': 'IsSupplementTo'}, {'relatedIdentifier': {'relatedIdentifier': '10.5452/ma-2bzsh'}, 'relatedIdentifierType': 'DOI', 'relationType': 'References'}], 'geoLocations': [{'geoLocation': {'geoLocationCountry': 'GERMANY', 'geoLocationRegion': 'North-Rhine Westphalia, Rhineland-Platinate', 'geoLocationPoint': '00000', 'geoLocationBox': '11111'}}], 'dataSources': [{'dataSource': {'dataSource': 'Waters e2695 chromatography workstation with photodiode array detector (PDA) and a QDA mass detector (Waters)'}, 'dataSourceDetail': 'Instrument'}, {'dataSource': {'dataSource': 'BioRad CFX ConnectTM Real-Time System'}, 'dataSourceDetail': 'Instrument'}], 'software': [{'softwareType': {'softwareName': {'softwareName': 'Microsoft Office', 'softwareVersion': '2013'}}}, {'softwareType': {'softwareName': {'softwareName': 'Waters Empower', 'softwareVersion': '3'}, 'alternativeSoftwareName': {'alternativeSoftwareName': 'R', 'alternativeSoftwareVersion': '3.6.2'}}}], 'processing': [{'dataProcessing': {'dataProcessing': 'Kollisionsdetektion'}}], 'relatedInformations': [{'relatedInformation': {'relatedInformation': 'DOI Journal Article'}, 'relatedInformationType': '10.1038/s42003-021-01967-9'}], 'fundingReferences': [{'fundingReference': {'funderName': 'Landwirtschaftliche Rentenbank', 'funderIdentifier': {'funderIdentifier': 'Project No. 182849149 (SFB 953)', 'type': 'Other'}, 'awardNumber': 'UBO 53C-50009_00_71030002', 'awardURI': 'https://gepris.dfg.de/gepris/projekt/318064602', 'awardTitle': 'Biosynthese der Piperamide im schwarzen Pfeffer (Piper nigrum)'}}]}}},
                                    {'header': {'identifier': '10.22000/152', 'datestamp': '2022-04-04T09:06:49Z'}, 'metadata': {'radarDataset': {'identifier': {'identifier': '10.22000/152', 'identifierType': 'DOI'}, 'creators': [{'creator': {'creatorName': 'Schughart, Klaus', 'givenName': 'Klaus', 'familyName': 'Schughart', 'creatorAffiliation': 'Helmholtz Centre for Infection Research', 'nameIdentifier': {'nameIdentifier': '0000-0002-6824-7523', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}], 'title': 'data and codes for publication Tang et al 2019', 'publishers': [{'publisher': {'publisher': 'Klaus Schughart'}}], 'productionYear': '2019', 'publicationYear': '2019', 'subjectAreas': [{'subjectArea': {'controlledSubjectAreaName': 'Medicine'}}], 'resource': {'resource': 'Data and R codes', 'resourceType': 'Dataset'}, 'rights': [{'rights': {'controlledRights': 'CC BY 4.0 Attribution'}}], 'rightsHolders': [{'rightsHolder': {'rightsHolder': 'Klaus Schughart'}}], 'additionalTitles': [], 'descriptions': [], 'keywords': [], 'contributors': [], 'language': {}, 'alternateIdentifiers': [], 'relatedIdentifiers': [], 'geoLocations': [], 'dataSources': [], 'software': [], 'processing': [], 'relatedInformations': [], 'fundingReferences': []}}},
                                    {'header': {'identifier': '10.22000/155', 'datestamp': '2022-04-04T09:06:49Z'}, 'metadata': {'radarDataset': {'identifier': {'identifier': '10.22000/155', 'identifierType': 'DOI'}, 'creators': [{'creator': {'creatorName': 'Meng, Jilun', 'givenName': 'Jilun', 'familyName': 'Meng', 'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)', 'nameIdentifier': {'nameIdentifier': '0000-0003-0665-7655', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}, {'creator': {'creatorName': 'Mayer, Manfred', 'givenName': 'Manfred', 'familyName': 'Mayer', 'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)', 'nameIdentifier': {'nameIdentifier': '0000-0002-6382-2533', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}, {'creator': {'creatorName': 'Reinsch, Norbert', 'givenName': 'Norbert', 'familyName': 'Reinsch', 'creatorAffiliation': 'Institute of Genetics and Biometry, Leibniz-Institute for Farm Animal Biology (FBN)', 'nameIdentifier': {'nameIdentifier': '0000-0001-7435-4088', 'schemeURI': 'http://orcid.org/', 'nameIdentifierScheme': 'ORCID'}}}], 'title': 'Turning observed founder alleles into expected relationships - example programs', 'publishers': [{'publisher': {'publisher': 'Leibniz Institute for Farm Animal Biology (FBN)'}}], 'productionYear': '2019', 'publicationYear': '2019', 'subjectAreas': [{'subjectArea': {'controlledSubjectAreaName': 'Agriculture'}}, {'subjectArea': {'controlledSubjectAreaName': 'Life Science'}}], 'resource': {'resource': 'example program, input and output examples', 'resourceType': 'Software'}, 'rights': [{'rights': {'controlledRights': 'CC BY 4.0 Attribution'}}], 'rightsHolders': [{'rightsHolder': {'rightsHolder': 'Leibniz Institute for Farm Animal Biology (FBN)'}}], 'additionalTitles': [], 'descriptions': [{'description': {'description': 'Example programs are presented that can be used to compute expected relationships in a two-way cross where the founders have been genotyped. Theory is described in very detail in the article of Meng et al. "Turning Observed Founder Alleles into Expected Relationships in an Intercross Population", published in G3: Genes, Genomes, Genetics (2019 vol. 9 no. 3 889-899) and accessible under  https://doi.org/10.1534/g3.118.200752 . Together with the programs example data are provided. A further detailed description is given in the readme-file that is included.'}, 'descriptionType': 'Method'}], 'keywords': [{'keyword': {'keyword': 'relationship matrix, expected relationships, founder relationships'}}], 'contributors': [], 'language': 'eng', 'alternateIdentifiers': [], 'relatedIdentifiers': [], 'geoLocations': [], 'dataSources': [], 'software': [{'softwareType': {'softwareName': {'softwareName': 'R', 'softwareVersion': 'R version 3.5.2'}}}], 'processing': [], 'relatedInformations': [], 'fundingReferences': []}}}]


radar_all_datasets_list_response = [{'repository_name': 'RADAR (Research Data Repository)', 'type': 'vdataset', 'source_metadata_created': '2019', 'source_metadata_modified': '', 'owner_org': 'radar', 'author': 'Schughart, Klaus', 'author_email': '', 'doi': '10.22000/152X', 'doi_date_published': '2019', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC BY 4.0 Attribution', 'license_title': 'Licenses of the images according to image_licenses.csv', 'name': 'rdr-doi-10-22000-152x', 'notes': 'Abstract: The dataset contains the data underlying the plots and histograms in the article "Collective photon emission patterns from two atoms in free space". The data show the photon statistics of a trapped two-ion crystal observed in the far-field.  Details of the measurement process and experimental setup can be found in the journal publication. The data for each individual plot are presented as a table in a separate sheet in an xlsx-spreadsheet.\r\nOther: Interviewtranskripte, Fragebogenauswertungen', 'organization': {'approval_status': 'approved', 'description': 'RADAR (Research Data Repository) is a cross-disciplinary repository for archiving and publishing research data from completed scientific studies and projects. The focus is on research data from subjects that do not yet have their own discipline-specific infrastructures for research data management. ', 'display_name': 'RADAR', 'image_display_url': '/images/radar-logo.png', 'image_url': '/images/radar-logo.png', 'is_organization': True, 'name': 'radar', 'state': 'active', 'title': 'RADAR', 'type': 'organization'}, 'title': 'Data and codes for publication tang et al 2019', 'url': 'https://doi.org/10.22000/152X', 'orcid': '0000-0002-6824-7523', 'extra_authors': [{'extra_author': 'Mayer, Manfred', 'orcid': '0000-0002-6382-2533'}, {'extra_author': 'Reinsch, Norbert', 'orcid': '0000-0001-7435-4088'}], 'tags': [{'display_name': 'downy mildew resistance', 'name': 'downy mildew resistance', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'untargeted metabolomics', 'name': 'untargeted metabolomics', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'genome-wide association study', 'name': 'genome-wide association study', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'phenylpropanoids', 'name': 'phenylpropanoids', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'hop', 'name': 'hop', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'oomycete', 'name': 'oomycete', 'state': 'active', 'vocabulary_id': None}], 'publishers': [{'publisher': 'Klaus Schughart'}, {'publisher': 'Putnings, Markus'}], 'production_year': '2019', 'publication_year': '2019', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Medicine'}, {'subject_area_additional': 'Bibliotheks- und Informationswissenschaft', 'subject_area_name': 'Other'}], 'resource_type': 'Dataset - Data and R codes'},
                                    {'repository_name': 'RADAR (Research Data Repository)', 'type': 'vdataset', 'source_metadata_created': '2019', 'source_metadata_modified': '', 'owner_org': 'radar', 'author': 'Schughart, Klaus', 'author_email': '', 'doi': '10.22000/152', 'doi_date_published': '2019', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC BY 4.0 Attribution', 'license_title': '', 'name': 'rdr-doi-10-22000-152', 'notes': '', 'organization': {'approval_status': 'approved', 'description': 'RADAR (Research Data Repository) is a cross-disciplinary repository for archiving and publishing research data from completed scientific studies and projects. The focus is on research data from subjects that do not yet have their own discipline-specific infrastructures for research data management. ', 'display_name': 'RADAR', 'image_display_url': '/images/radar-logo.png', 'image_url': '/images/radar-logo.png', 'is_organization': True, 'name': 'radar', 'state': 'active', 'title': 'RADAR', 'type': 'organization'}, 'title': 'Data and codes for publication tang et al 2019', 'url': 'https://doi.org/10.22000/152', 'orcid': '0000-0002-6824-7523', 'publishers': [{'publisher': 'Klaus Schughart'}], 'production_year': '2019', 'publication_year': '2019', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Medicine'}], 'resource_type': 'Dataset - Data and R codes'},
                                    {'repository_name': 'RADAR (Research Data Repository)', 'type': 'vdataset', 'source_metadata_created': '2019', 'source_metadata_modified': '', 'owner_org': 'radar', 'author': 'Meng, Jilun', 'author_email': '', 'doi': '10.22000/155', 'doi_date_published': '2019', 'doi_publisher': '', 'doi_status': 'True', 'license_id': 'CC BY 4.0 Attribution', 'license_title': '', 'name': 'rdr-doi-10-22000-155', 'notes': 'Method: Example programs are presented that can be used to compute expected relationships in a two-way cross where the founders have been genotyped. Theory is described in very detail in the article of Meng et al. "Turning Observed Founder Alleles into Expected Relationships in an Intercross Population", published in G3: Genes, Genomes, Genetics (2019 vol. 9 no. 3 889-899) and accessible under  https://doi.org/10.1534/g3.118.200752 . Together with the programs example data are provided. A further detailed description is given in the readme-file that is included.', 'organization': {'approval_status': 'approved', 'description': 'RADAR (Research Data Repository) is a cross-disciplinary repository for archiving and publishing research data from completed scientific studies and projects. The focus is on research data from subjects that do not yet have their own discipline-specific infrastructures for research data management. ', 'display_name': 'RADAR', 'image_display_url': '/images/radar-logo.png', 'image_url': '/images/radar-logo.png', 'is_organization': True, 'name': 'radar', 'state': 'active', 'title': 'RADAR', 'type': 'organization'}, 'title': 'Turning observed founder alleles into expected relationships - example programs', 'url': 'https://doi.org/10.22000/155', 'orcid': '0000-0003-0665-7655', 'extra_authors': [{'extra_author': 'Mayer, Manfred', 'orcid': '0000-0002-6382-2533'}, {'extra_author': 'Reinsch, Norbert', 'orcid': '0000-0001-7435-4088'}], 'tags': [{'display_name': 'relationship matrix', 'name': 'relationship matrix', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'expected relationships', 'name': 'expected relationships', 'state': 'active', 'vocabulary_id': None}, {'display_name': 'founder relationships', 'name': 'founder relationships', 'state': 'active', 'vocabulary_id': None}], 'publishers': [{'publisher': 'Leibniz Institute for Farm Animal Biology (FBN)'}], 'production_year': '2019', 'publication_year': '2019', 'subject_areas': [{'subject_area_additional': '', 'subject_area_name': 'Agriculture'}, {'subject_area_additional': '', 'subject_area_name': 'Life Science'}], 'resource_type': 'Software - example program, input and output examples'}]

ckan_dict_of_imported_dataset = {
        "author": "Schughart, Klaus",
        "author_email": "",
        "creator_user_id": "17755db4-395a-4b3b-ac09-e8e3484ca700",
        "doi": "10.22000/152",
        "doi_date_published": "2019",
        "doi_publisher": "",
        "doi_status": "True",
        "id": "7a1dfab5-68bf-4083-ba76-c0e1a6b00439",
        "isopen": False,
        "license_id": "CC BY 4.0 Attribution",
        "license_title": "CC BY 4.0 Attribution",
        "metadata_created": "2022-07-25T10:54:46.377712",
        "metadata_modified": "2022-07-25T10:54:46.377723",
        "name": "rdr-doi-10-22000-152",
        "notes": "",
        "num_resources": 0,
        "num_tags": 0,
        "orcid": "0000-0002-6824-7523",
        "organization": {
            "id": "2f621afe-f0ee-4c40-ace4-112f491c66b6",
            "name": "radar",
            "title": "RADAR",
            "type": "organization",
            "description": "RADAR (Research Data Repository) is a cross-disciplinary repository for archiving and publishing research data from completed scientific studies and projects. The focus is on research data from subjects that do not yet have their own discipline-specific infrastructures for research data management. ",
            "image_url": "https://radar.products.fiz-karlsruhe.de/themes/custom/fizweb/icons/radar/logo-radar-en.svg",
            "created": "2022-07-25T10:42:16.843717",
            "is_organization": True,
            "approval_status": "approved",
            "state": "active"
        },
        "owner_org": "2f621afe-f0ee-4c40-ace4-112f491c66b6",
        "private": False,
        "production_year": "2019",
        "publication_year": "2019",
        "repository_name": "RADAR (Research Data Repository)",
        "resource_type": "Dataset - Data and R codes",
        "source_metadata_created": "2019",
        "source_metadata_modified": "",
        "state": "active",
        "title": "Data and codes for publication tang et al 2019",
        "type": "vdataset",
        "url": "https://doi.org/10.22000/152",
        "publishers": [
            {
                "publisher": "Klaus Schughart"
            }
        ],
        "subject_areas": [
            {
                "subject_area_additional": "",
                "subject_area_name": "Medicine"
            }
        ],
        "resources": [],
        "tags": [],
        "groups": [],
        "relationships_as_subject": [],
        "relationships_as_object": []
    }


radar_dict_of_imported_dataset = radar_all_datasets_list_response[1]