
no_resource_resp = {'count': 0, 'results': []}


daily_resource_resp = {'count': 1,
                       'results': [{'id': 'd38595e6-1d41-42f7-a814-0317ca79172b',
                                    'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                    'url': 'http://test.ckan.net/dataset/476cdf71-1048-4a6f-a28a-58fff547dae5/resource/d38595e6-1d41-42f7-a814-0317ca79172b/download/resource_update_daily.txt',
                                    'format': 'TXT',
                                    'description': '',
                                    'hash': '',
                                    'position': 3,
                                    'name': 'Test update daily',
                                    'resource_type': None,
                                    'mimetype': 'text/plain',
                                    'mimetype_inner': None,
                                    'size': 24,
                                    'created': '2022-02-21T09:04:13.977617',
                                    'last_modified': '2022-02-21T09:04:13.932237',
                                    'metadata_modified': '2022-02-21T09:05:28.130731',
                                    'cache_url': None,
                                    'cache_last_updated': None,
                                    'url_type': 'upload',
                                    'state': 'active',
                                    'auto_update': 'Daily',
                                    'auto_update_url': 'https://www.dropbox.com/s/xeape25rn653uqo/resource_update_daily.txt?dl=0',
                                    'datastore_active': False}]}

weekly_resource_resp = {'count': 1,
                        'results': [{'id': 'c2fccbf7-05ce-4f35-8640-b91464ffcf7f',
                                     'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                     'url': 'http://test.ckan.net/dataset/476cdf71-1048-4a6f-a28a-58fff547dae5/resource/c2fccbf7-05ce-4f35-8640-b91464ffcf7f/download/resource_update_weekly.txt',
                                     'format': 'TXT',
                                     'description': '',
                                     'hash': '',
                                     'position': 4,
                                     'name': 'Test update weekly',
                                     'resource_type': None,
                                     'mimetype': 'text/plain',
                                     'mimetype_inner': None,
                                     'size': 25,
                                     'created': '2022-02-21T09:05:28.137767',
                                     'last_modified': '2022-02-21T09:05:28.109070',
                                     'metadata_modified': '2022-02-21T09:06:06.973079',
                                     'cache_url': None,
                                     'cache_last_updated': None,
                                     'url_type': 'upload',
                                     'state': 'active',
                                     'auto_update': 'Weekly',
                                     'auto_update_url': 'https://www.dropbox.com/s/nbdis48czdkzgro/resource_update_weekly.txt?dl=0',
                                     'datastore_active': False}]}

monthly_resource_resp = {'count': 1,
                         'results': [{'id': 'dc62a799-db41-4a9b-acc1-8e289d4e1897',
                                      'package_id': '476cdf71-1048-4a6f-a28a-58fff547dae5',
                                      'url': 'http://test.ckan.net/dataset/476cdf71-1048-4a6f-a28a-58fff547dae5/resource/dc62a799-db41-4a9b-acc1-8e289d4e1897/download/resource_update_monthly.txt',
                                      'format': 'TXT',
                                      'description': '',
                                      'hash': '',
                                      'position': 5,
                                      'name': 'Test update monthly',
                                      'resource_type': None,
                                      'mimetype': 'text/plain',
                                      'mimetype_inner': None,
                                      'size': 26,
                                      'created': '2022-02-21T09:06:06.980281',
                                      'last_modified': '2022-02-21T09:06:06.951294',
                                      'metadata_modified': '2022-02-21T09:06:06.973404',
                                      'cache_url': None,
                                      'cache_last_updated': None,
                                      'url_type': 'upload',
                                      'state': 'active',
                                      'auto_update': 'Monthly',
                                      'auto_update_url': 'https://www.dropbox.com/s/pntofkk1uzx8yu1/resource_update_monthly.txt?dl=0'}]}

file_request_header = {'Server': 'nginx',
                       'Date': 'Tue, 22 Feb 2022 08:26:26 GMT',
                       'Content-Type': 'application/zip',
                       'Content-Length': '10485760',
                       'Last-Modified': 'Mon, 02 Jun 2008 15:30:33 GMT',
                       'Connection': 'keep-alive',
                       'ETag': '"48441219-a00000"',
                       'Access-Control-Allow-Origin': '*',
                       'Accept-Ranges': 'bytes'}